### PR TITLE
fix(core/caniuse): update browser logos URL

### PR DESCRIPTION
**Pull request by marcoscaceres**
The icons might be moving to this URL instead....

### CODE REVIEW

**Comment by sidvishnoi** [comment]
Might want to do it for mdn panels too?

**Comment by marcoscaceres** [comment]
Yeah, spotted that. Would be good to have a single source.

**Comment by Mwoodin123** [comment]
I dont know how why I signed up for these emails. I am no where smart enough to know about any of this. Why am I getting these?

**Comment by marcoscaceres** [comment]
@Mwoodin123 you must Be following this repo or have accidentally subscribed to this issue.

**Comment by plehegar** [comment]
Use  https://cdn.w3.org/assets/logos/w3c/browser-logos/*
eg
  https://cdn.w3.org/assets/logos/w3c/browser-logos/chrome/chrome_16x16.png

**Comment by sidvishnoi** [comment]
@plehegar is there a list of available files somewhere?

**Comment by plehegar** [comment]
Yes, the files come4 from the repo https://github.com/w3c/logos .
See https://github.com/w3c/logos/tree/main/browser-logos

**Review by sidvishnoi — APPROVED** [review]

**Pull request merged**
