### PR TITLE
Chore(global) deprecate 'webspec' status support (closes #715)

### LINKED ISSUE #715: Remove support for webspec
As "webspec" status is now deprecated (defaults to unofficial), we should remove the dead code from headers.js

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Bye bye "webspec", we hardly knew ye! 😢 👋

**Comment by marcoscaceres** [comment]
@tripu, all good to drop "webspec" status, right? My understanding is that it's not used on the w3c side. 

cc @dontcallmedom.

**Comment by tripu** [comment]
@marcoscaceres:

* Is [`examples/respec-debug.js`](https://github.com/w3c/respec/blob/develop/examples/respec-debug.js) regenerated automatically?
* [`js/core/css/examples-webspecs.css`](https://github.com/w3c/respec/blob/develop/js/core/css/examples-webspecs.css) mentions &ldquo;EXAMPLES CONFLICTING WITH WEBSPECS&rdquo;. Maybe the file is not necessary any more?

AFAIK, we can get rid of `webspecs`, yes. But I'm not familiar with the internals of ReSpec, really.

Over to @dontcallmedom or @halindrome to triple-check.

**Comment by marcoscaceres** [comment]
> On 10 May 2016, at 8:42 PM, tripu <notifications@github.com> wrote:
> 
> @marcoscaceres:
> 
> Is examples/respec-debug.js regenerated automatically?

No. But will add a task to do that (or to delete it). 

> js/core/css/examples-webspecs.css mentions “EXAMPLES CONFLICTING WITH WEBSPECS”. Maybe the file is not necessary any more?
> AFAIK, we can get rid of webspecs, yes. But I'm not familiar with the internals of ReSpec, really.
> 
> Over to @dontcallmedom or @halindrome to triple-check.
> 

It's more of a question about if the Webspecs project died. It seems it did, but wanted confirmation.

**Comment by dontcallmedom** [comment]
No objection from me (not that I have any particularly useful insights); that said, I think it would be nice in the future that before deprecating a type of document, we start with emitting warnings.

**Comment by tripu** [comment]
@marcoscaceres, I didn't know about Webspecs in ReSpec until I noticed that the CSS in [modern-tooling](https://w3c.github.io/modern-tooling/) was broken, so&hellip; :)

(What about editing `js/core/css/examples-webspecs.css`, then?)

**Comment by marcoscaceres** [comment]
> (What about editing js/core/css/examples-webspecs.css, then?)

I'll delete it instead, as it doesn't apply.

**Pull request merged**
