### PR TITLE
fix(styles/ui): respect prefers-reduced-motion, cooler loading animation

### LINKED ISSUE #4193: turn off (or make quicker) the animations to respect reduced-motion preferences
## Description of problem

Certain actions in specs cause a keyframes "pop" animation

**URL to affected spec or repo:**

https://w3c.github.io/aria/

**What happened (e.g., it crashed)?:**

Animation occurs even when reduce-motion OS preference is on

**Expected behavior (e.g., it shouldn't crash):**

A spec shouldn't need animation. Suggest to use media query to prevent this animation when reduce motion is enabled

**Optional, steps to reproduce:**

* go to spec
* click on informative or normative references link

### PR DESCRIPTION
**Pull request by fycdev**
### Disable animation of respec-pill when prefers-reduced-motion is true

Fixes #4193 

Not sure if this requires a test and if so would it be under `tests/spec/core/ui-spec.js`?

### CODE REVIEW

**Comment by fycdev** [comment]
Will also be updating the `respect-pill` button styles alongside this fix as described by @marcoscaceres 👍

**Review by sidvishnoi — APPROVED** [review]
Love that morphing effect, @fycdev!

**Comment by sidvishnoi** [comment]
And no, no need for tests for this.

**Review by marcoscaceres — APPROVED** [review]
lgtm! Nice one @fycdev!

**Pull request merged**
