### PR TITLE
style: apply spaced-comment eslint rule

### PR DESCRIPTION
**Pull request by saschanaz**
This forces spaces after `//`, `/*` and before `*/`.

### CODE REVIEW

**Comment by saschanaz** [comment]
BTW is anyone using jshint here? @marcoscaceres @sidvishnoi

**Comment by marcoscaceres** [comment]
Not anymore.

**Comment by saschanaz** [comment]
Can `/* jshint */` comments be removed now then?

**Comment by marcoscaceres** [comment]
Yep, feel fre to remove.

**Pull request merged**
