### PR TITLE
l10n: update zh and ja translations

### PR DESCRIPTION
**Pull request by xfq**
This PR upstreams the changes in https://github.com/w3c/jlreq/pull/61 and updates some other zh and ja translations.

/cc @r12a @himorin

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Assuming these are ok :)

**Comment by r12a** [comment]
Thanks @marcoscaceres. We checked the Japanese ones with the jlreq folks, and Fuqiao is Chinese, so should be no worries.

**Comment by marcoscaceres** [comment]
Appreciate that. I'll do a release first thing tomorrow so they show up in your specs.

**Comment by marcoscaceres** [comment]
Pushed out a new version of ReSpec, which includes these.

**Comment by r12a** [comment]
Thanks, Marcos.

**Pull request merged**
