### PR TITLE
Fix using karma-edge-launcher on local tests

### PR DESCRIPTION
**Pull request by nickmccurdy**
## Notes
- Disables IE testing
- Enables Edge testing with [karma-edge-launcher](https://github.com/nickmccurdy/karma-edge-launcher)
- Fixes a bug in karma-detect-browsers which would cause builds to fail on systems that don't have Edge

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@nickmccurdy, I'm a little hesitant to switch away from "karma-detect-browsers" to your fork, as we release quite often. What's blocking integration of your branch into karma-detect-browsers (assuming you sent them a PR)?

**Comment by nickmccurdy** [comment]
That's a good point, you might want to wait. I was intending for it to point to my fork temporarily, as I do have a [PR open](https://github.com/litixsoft/karma-detect-browsers/pull/15). The pull request is failing, and I haven't figured out why yet (it seems like a Travis-specific issue since my local tests passed).

**Comment by marcoscaceres** [comment]
Ok, closing this for now.

**Comment by nickmccurdy** [comment]
karma-detect-browsers has merged in my pull request, and now supports karma-edge-launcher as of version 2.2.0.

**Comment by nickmccurdy** [comment]
I'm waiting for this issue to be fixed: https://github.com/litixsoft/karma-detect-browsers/issues/17

Then I'll start a new pull request (or ask you to reopen this one if you prefer).

**Comment by marcoscaceres** [comment]
I've reopened this one for you. Let me know when it's all good to go 👍

**Comment by nickmccurdy** [comment]
Waiting on a fix for https://github.com/litixsoft/karma-detect-browsers/issues/17.

**Comment by marcoscaceres** [comment]
@nickmccurdy, please rebase when you get a chance.

**Comment by marcoscaceres** [comment]
@nickmccurdy when you are ready, let me know how to proceed.

**Comment by nickmccurdy** [comment]
Sorry for the delay. I rebased the fix, it should be good now.

**Comment by marcoscaceres** [comment]
updated code to use functional style - as is convention in the rest of the project.

**Comment by nickmccurdy** [comment]
Good point, it's simpler with `.filter()`.

**Pull request merged**
