### PR TITLE
eslint: prevent eval()

### PR DESCRIPTION
**Pull request by tripu**

### CODE REVIEW

**Comment by saschanaz** [comment]
Um... also pinging @marcoscaceres, following https://github.com/w3c/webidl2.js/pull/234#issuecomment-434322647.

**Comment by saschanaz** [comment]
The package-lock.json changes don't look good. What happened there?

**Comment by marcoscaceres** [comment]
@tripu, would you mind excluding the package-lock file? We will regenerate it.

**Comment by tripu** [comment]
@marcoscaceres: done.

(Why don't you guys commit changes to `packages-lock.json`? Or add it to `.gitignore`?)

**Comment by marcoscaceres** [comment]
We do commit it, but as part of our dependency update process. So we like to do it automatically as part of the release process.

**Pull request merged**
