### PR TITLE
fix(core/inlines): RegExp syntax error 🔥

### PR DESCRIPTION
**Pull request by marcoscaceres**
Broke Safari and Firefox, yay! 🥳

### CODE REVIEW

**Comment by saschanaz** [comment]
Might be great if we have a tracking issue on Firefox side.

**Comment by marcoscaceres** [comment]
Yeah, agree... I honestly don't even know what to search for.

**Comment by marcoscaceres** [comment]
maybe https://bugzilla.mozilla.org/show_bug.cgi?id=1362154

**Comment by saschanaz** [comment]
"Regex lookahead" seems the right keyword. AFAIK named group is another separate feature.

**Comment by marcoscaceres** [comment]
Might need also try enabling Firefox again on Travis... so flaky tho... but maybe better since last time, specially now that we can do headless mode.

**Comment by saschanaz** [comment]
Actually "lookbehind", the relevant issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1225665

**Comment by marcoscaceres** [comment]
Thank for finding it.

**Pull request merged**
