### PR TITLE
Added dependency on Promise early

### PR DESCRIPTION
**Pull request by halindrome**
Forces load.  Seems to resolve packaging issue.

### CODE REVIEW

**Comment by halindrome** [comment]
arrgh - how the heck can this have a merge conflict?  I just checked out develop!!

**Comment by marcoscaceres** [comment]
I merged the other two PRs :)

**Comment by halindrome** [comment]
Hmm - irc?

**Comment by halindrome** [comment]
I honestly loathe git.  low tech crap.  it was PERFECT.  Now I have to somehow.... no idea.

**Comment by marcoscaceres** [comment]
Actually, when you 'git rebase develop' from your branch, you can just use my version of profile-w3c-common.js ('git checkout --ours js/profile-w3c-common.js')

**Comment by halindrome** [comment]
Nope - doesn't work.  Screw it.  I will do it over.  PLEASE DONT DO ANYTHING FOR A MINUTE.

**Comment by marcoscaceres** [comment]
Note you might also want to add Promise as a dep on core/respec-ready.js, as it also needs it early.

**Comment by halindrome** [comment]
It already has that as a dep?

**Comment by marcoscaceres** [comment]
Not sure, I think it just assumes that Promises are on the window object. The polyfill is supposed to just do that.

**Comment by marcoscaceres** [comment]
I lied. It's there: https://github.com/w3c/respec/blob/develop/js/core/respec-ready.js

**Pull request closed without merging**
