### PR TITLE
refactor(tests): Deprecate SpecRunner.html and move to html reporter

### LINKED ISSUE #2244: Deprecate SpecRunner.js
We have two ways of running tests... SpecRunner and Karma... we should only have one: Karma. 

We should look at removing SpecRunner.html and make sure any documentation that lists it gets updated too.

### PR DESCRIPTION
**Pull request by Swapnilr1**
Fixes #2244 

I will update the Developers Guide also.

### CODE REVIEW

**Comment by Swapnilr1** [comment]
Yup, I also find `SpecRunner` more convenient than running karma tests, and once ReSpec moves to webpack I would definitely want to see if this can be patched and added back.

**Comment by marcoscaceres** [comment]
We should check https://www.npmjs.com/package/karma-jasmine-html-reporter

**Comment by Swapnilr1** [comment]
> We should check https://www.npmjs.com/package/karma-jasmine-html-reporter

Great! Will look into it once my existing PRs are merged.

**Comment by Swapnilr1** [comment]
OK, this was easy to add.

**Comment by marcoscaceres** [comment]
Tested locally with BROWSERS set... works great!

**Pull request merged**
