### PR TITLE
fix: roll back to uglify-es 3.2.2

### LINKED ISSUE #1458: Test failure: 'root' is deprecated, use 'global'
https://travis-ci.org/w3c/respec/jobs/335038255

Not sure what happened there...

### PR DESCRIPTION
**Pull request by saschanaz**
Fixes #1458 

It turns out that the recent update of uglify-es is the culprit.

(This includes #1459 so you will probably want to merge it first)

### CODE REVIEW

**Comment by saschanaz** [comment]
Probably worth trying babel-minify, BTW.

**Comment by marcoscaceres** [comment]
Nice find! 🕵️‍♂️

**Comment by marcoscaceres** [comment]
@saschanaz, will babel-minify allow us to get rid of the dependency on uglify? I guess we would only run it when we generate the packaged version.

**Comment by saschanaz** [comment]
Yes, we won't have to call babel and then uglify, we can just call babel-minify and that's it.

**Comment by marcoscaceres** [comment]
Ok, but it would be a hard requirement that we can generate a concatenated, but *not* minified, version for development... otherwise, debugging is going to be extremely hard. Sourcemaps are very very broken across browsers, so definitely don't want to be reliant on them (been there, done that, never again 🤪).

**Pull request merged**
