### PR TITLE
feat(assets/respec2): make inline warnings visually pop

### PR DESCRIPTION
**Pull request by marcoscaceres**
When clicking navigating to inline errors, or certain areas of interest, this makes the things "pop"... making them easier to find amongst other text.

### CODE REVIEW

**Comment by sidvishnoi** [comment]
Squiggly line is rendered twice, once as background image, then due to "text-decoration"
image

**Comment by sidvishnoi** [comment]
Also, can we make it a animation bit more visible? use a background maybe?

**Comment by marcoscaceres** [comment]
Will play around. Might make the background a bit yellow then fade to whatever it originally was

**Comment by sidvishnoi** [comment]
Looks like `ui.css` loaded before `respec2.css` giving us both underline and squiggly background.

**Comment by marcoscaceres** [comment]
> Will play around. Might make the background a bit yellow then fade to whatever it originally was

Played around with different background... none of them really looked good, tbh. I decided to stick with this for now. Can improve it over time.

**Comment by paulirish** [comment]
What a subtle and beautiful lil detail. ❤️

**Pull request merged**
