### PR TITLE
Backout fixup.js 

### PR DESCRIPTION
**Pull request by marcoscaceres**
It seems prudent to back out "fixup.js" because of code quality issues, lack of test, and code replication. 

We can work out a better strategy for testing the new 2016 design in ReSpec.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@halindrome, r?

**Comment by tripu** [comment]
Wouldn't it be better to keep the current code while you guys rewrite a better version?

The output of ReSpec won't meet the new pubrules (TR design 2016) in the interim&hellip;

**Comment by marcoscaceres** [comment]
> On 16 Feb 2016, at 8:55 PM, tripu <notifications@github.com> wrote:
> 
> Wouldn't it be better to keep the current code while you guys rewrite a better version?
> 
Tell you what: I'll only back out The current one when I finish the new one. 
> The output of ReSpec won't meet the new pubrules (TR design 2016) in the interim…
> 
Understood. Expect a pull request from me in the next day or two.

**Comment by plehegar** [comment]
I just sync'ed fixup,js with upstream. If there are bugs with it, those should be filled in https://github.com/w3c/tr-design. But the current expectation is to make it mandatory for publication.

**Comment by marcoscaceres** [comment]
@plehegar, @tripu, please see/review https://github.com/w3c/respec/pull/571

**Comment by marcoscaceres** [comment]
@plehegar wrote:
> I just sync'ed fixup,js with upstream. 

I rewrote fixup.js to work better with ReSpec (and made a few improvements in the process). It now listens for ReSpec's "end-all" callback.  
https://github.com/w3c/tr-design/pull/55

**Comment by marcoscaceres** [comment]
Backed out in prep for #571.

**Pull request merged**
