### PR TITLE
Javascript errors shouldn't appear in the output

### PR DESCRIPTION
**Pull request by plehegar**
Otherwise spec-generator can't generate properly the clipboard-apis spec.

### CODE REVIEW

**Comment by halindrome** [comment]
Umm - I don't *disagree* but... what javascript errors?

**Comment by marcoscaceres** [comment]
@plehegar, this seems fine - but I also want a little bit more info before we merge.

**Comment by plehegar** [comment]
http://w3c.github.io/clipboard-apis/
 generates Javascript errors on the console, because it embeds tests. I assume those are taken and run separately.

spec-generator uses respec2html to convert a respec doc into a TR ready one. See the result on clipboard-apis:
 https://labs.w3.org/spec-generator/?type=respec&url=http%3A%2F%2Fw3c.github.io%2Fclipboard-apis%2Findex.html%3FspecStatus%3DWD%3BshortName%3Dclipboard-apis

so the change is meant to mute those errors so that they don't end up in the output.

**Comment by halindrome** [comment]
Okay, I get it!  Thanks.  BTW why does the spec have javascript errors in it?

**Pull request merged**
