### PR TITLE
fix(core/structure): trim section titles

### PR DESCRIPTION
**Pull request by marcoscaceres**
Removes extra whitespace that can occur in the titles (also refactor code a little bit). 

screenshot 2019-01-31 17 23 38

### CODE REVIEW

**Comment by saschanaz** [comment]
Somehow the test is failing.

**Comment by marcoscaceres** [comment]
Having a look. Need to trim() in the test, I think.

**Comment by saschanaz** [comment]
I'm not loving force pushes... 🤔

**Comment by marcoscaceres** [comment]
Apologies, picked up bad habits 🚬.

**Pull request merged**
