### PR TITLE
Process 2019 link

### PR DESCRIPTION
**Pull request by plehegar**
DO NOT MERGE BEFORE MARCH 1

This is this time of the year again.

Part of
  https://github.com/w3c/modern-tooling/issues/84

### CODE REVIEW

**Comment by plehegar** [comment]
I guess conf.processVersion is gone because I didn't find it.

**Comment by marcoscaceres** [comment]
Checked the history, we ditched `processVersion` a while back:
https://github.com/w3c/respec/pull/1480#issuecomment-364817515

**Comment by plehegar** [comment]
I removed the build changes.

**Comment by plehegar** [comment]
(re-aligned with latest develop commits)

**Comment by plehegar** [comment]
respec rocks!

**Comment by marcoscaceres** [comment]
Ok, this is now both in the latest release and in the spec generator.

**Pull request merged**
