### PR TITLE
Github links should include link to pull requests #1373

### PR DESCRIPTION
**Pull request by OrionStar25**

### CODE REVIEW

**Comment by OrionStar25** [comment]
@marcoscaceres can you please review this? thanks

**Comment by OrionStar25** [comment]
@marcoscaceres Should we be updating the docs related to this? 
[Like this one](https://github.com/w3c/respec/wiki/github)
Or is there another workflow for that?

**Comment by marcoscaceres** [comment]
@OrionStar25, good question... `pullBase` is mostly internal, so we probably don't want people using it directly, right? 

However, in the "github:" wiki page, have a look to see if the description that is there makes sense.

**Comment by OrionStar25** [comment]
> It also adds an object to otherLinks for under "Participate", with the appropriate links to your github repository.
Since pullBase does add an object to otherLinks, and is automatically generated after giving a repoURL, I thought it should be included as well. Please tell me if I'm interpreting it wrongly though!

**Comment by marcoscaceres** [comment]
So, consider the following ReSpec configuration:

```
      var respecConfig = {
        specStatus: "ED",
        editors: [{
          name: "Your Name",
          url: "https://your-site.com",
        }],
        github: "https://github.com/w3c/some-API/",
        pullBase: "foo"
      };
```

Adding `pullBase` above has no effect on the final pull request URL, right? So, for us to include it in the documentation, it would need to allow the spec author to override the pull request URL. 

Make sense?

**Comment by OrionStar25** [comment]
Makes absolute sense! Thanks for clarifying that 💃

**Pull request merged**
