### PR TITLE
fix(core/ui): update aria-label as errors/warnings are added

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by sidvishnoi** [comment]
Wouldn't this result in too many error announcements, which would be annoying? Maybe we should announce errors collectively at the end (n Respec errors, m Respec warnings)

**Comment by marcoscaceres** [comment]
I'm not sure, tbh. We are updating the label, but we are not asking the AT to announce anything? I don't imagine it randomly starts speaking if a label changes - but I'm not sure.

**Comment by sidvishnoi** [comment]
I'll check just to be sure 🙂

**Comment by sidvishnoi** [comment]
Checked with NVDA. It wasn't randomly announced like we were thinking. 
On hovering over error count though, it just announced the number, without any mention of what number it is. Focus worked as intended. Probably an NVDA issue

**Pull request merged**
