### PR TITLE
Use navigation role for TOC

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by plehegar** [comment]
LGTM

**Comment by anssiko** [comment]
This change breaks Pubrules Checker, see e.g.:

https://labs.w3.org/pubrules/?url=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fmanifest%2F%3FspecStatus%3DWD%3BshortName%3Dappmanifest&profile=WD-Echidna&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004&processDocument=2015

The error is:

>  [561@129] Bad value “navigation” for attribute “role” on element “ul”.

This means Echidna now refuses to publish documents authored with ReSpec.

An obvious fix would be to revert this change or fix Pubrules checker, whichever is right.

**Comment by stevefaulkner** [comment]
role=navigation on ul is non-conforming in HTML
http://w3c.github.io/html-aria/#ul

suggest adding role=navigation to <section id="toc" role="navigation"> and
no role on the <ul>

<ul id="respecContents" class="toc">

--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>

**Comment by marcoscaceres** [comment]
This is partially my fault. I had a PR sitting there that I should have closed, and PLH merged it.

I'll back that out tomorrow.

**Comment by halindrome** [comment]
I'm up - I will do it now.  Actually, I will move it to the section element
unless that conflicts with the new stylesheets.  Hang on.

On Fri, Nov 13, 2015 at 4:49 AM, Marcos Caceres <notifications@github.com>
wrote:

> This is partially my fault. I had a PR sitting there that I should have
> closed, and PLH merged it.
>
> I'll back that out tomorrow.
>
> Sent from my iPhone
>
>
> > On Nov 13, 2015, at 9:33 PM, stevefaulkner <notifications@github.com>
> wrote:
> >
> > role=navigation on ul is non-conforming in HTML
> > http://w3c.github.io/html-aria/#ul
> >
> > suggest adding role=navigation to <section id="toc" role="navigation">
> and
> > no role on the <ul>
> >
> > <ul id="respecContents" class="toc">
> >
> > --
> >
> > Regards
> >
> > SteveF
> > Current Standards Work @W3C
> > <
> http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>
> >
> > On 13 November 2015 at 10:25, Anssi Kostiainen <notifications@github.com
> >
> > wrote:
> >
> > > This change breaks Pubrules Checker, see e.g.:
> > >
> > >
> > >
> https://labs.w3.org/pubrules/?url=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fmanifest%2F%3FspecStatus%3DWD%3BshortName%3Dappmanifest&profile=WD-Echidna&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004&processDocument=2015
> > >
> > > The error is:
> > >
> > > [561@129] Bad value “navigation” for attribute “role” on element “ul”.
> > >
> > > This means Echidna now refuses to publish documents authored with
> ReSpec.
> > >
> > > An obvious fix would be to revert this change or fix Pubrules checker,
> > > whichever is right.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/w3c/respec/pull/499#issuecomment-156389460>.
> > >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/pull/499#issuecomment-156395372>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by halindrome** [comment]
I have a fix for this that should resolve he echidna issue.  Note that I personally don't feel this change is necessary at all.  role="directory" which we had on there before is also correct.  This is a static table of contents.

**Comment by marcoscaceres** [comment]
Agree about directory. I did some reading after I proposed the old PR and reached the same conclusion... But then never got around to closing the PR. We need a way of automatically checking changes against echidna.

**Comment by anssiko** [comment]
With https://github.com/w3c/respec/commit/98290f17ca1448630af033e2d46690facfe8a2b6 getting a different kind of error:

>[561@46] Bad value “navigation” for attribute “role” on element “section”.

**Comment by halindrome** [comment]
Of course it complains.  Seriously?  @marcoscaceres what do you propose?  Just back it out?  Revert it to directory?  @stevefaulkner do you have an opinion?

**Comment by marcoscaceres** [comment]
Yeah, let's back it out please. We can experiment outside the main branch.

**Comment by halindrome** [comment]
Okay.  On it.

**Comment by marcoscaceres** [comment]
Thanks, Shane, for handling this. You are a life saver!

**Comment by stevefaulkner** [comment]
@halindrome indeed the conformance requirements disallowed navigation on section, which seemed wonky as its default role is region and it allowed contentinfo and search, so have updated to allow all landmarks.
http://w3c.github.io/html-aria/#section

**Pull request merged**
