### PR TITLE
chore(tools/builder): minify CSS

### PR DESCRIPTION
**Pull request by sidvishnoi**
Reduces W3C bundle size by 8KB

### CODE REVIEW

**Comment by saschanaz** [comment]
How about gzipped size? 👀

**Comment by sidvishnoi** [comment]
> What about gzipped size? 👀

No change 👻

**Comment by saschanaz** [comment]
So no practical change. I'm afraid that this just complicates our build script...

**Comment by sidvishnoi** [comment]
No benefit with download, but that's 8kb less JavaScript to parse.

**Comment by sidvishnoi** [comment]
We can merge the functionality of `string` plugin in this. Might simplify (less plugins)

**Comment by saschanaz** [comment]
> No benefit with download, but that's 8kb less JavaScript to parse.

But it's just removing whitespaces, not really any optimization as JS minifiers do, right?

**Comment by sidvishnoi** [comment]
> But it's just removing whitespaces, not really any optimization as JS minifiers do, right?

Yep. But still less JavaScript to parse.

**Comment by saschanaz** [comment]
I think parsing whitespace is lightning fast on every engine...

**Comment by marcoscaceres** [comment]
Hhmm... @saschanaz does have a point. If it’s only white space, then it might not be worth adding the dependency.

**Comment by sidvishnoi** [comment]
It's whitespace, and a little bit of comments - all inside a JavaScript string. Let me confirm if there is no improvement in gzip size. If not, I'll close this.

**Comment by sidvishnoi** [comment]
``` diff
Size comparison (bytes):
- 294719
+ 286512
gzip:
- 92545
+ 91128
```

**Comment by sidvishnoi** [comment]
(I probably tested same gzip file earlier)

**Comment by sidvishnoi** [comment]
@saschanaz should I merge the functionality of `rollup-plugin-string` with this? One less dependency.

**Comment by saschanaz** [comment]
> should I merge the functionality of rollup-plugin-string with this? One less dependency.

I have no idea how it works, but please do!

**Pull request merged**
