### PR TITLE
Update to UI + base runner 

### PR DESCRIPTION
**Pull request by marcoscaceres**
I've reworked ReSpec's UI pill a bit... consolidated the CSS that was in code into the CSS file.  

Also, now that we have ES6 support in all browsers: 

 * Can simplify async code using generators. 
 * use some ES6 syntax for object literals, functions, etc.

screenshot 2016-09-23 19 51 33

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Added screenshot

**Comment by marcoscaceres** [comment]
This will be ReSpec (sem ver) v6.0.0.

**Comment by gkellogg** [comment]
Could we get the ReSpec version number in the About ReSpec dialog? I'm not seeing it there, presently. It might also be useful if it were in the body someplace, so that the version used to freeze a spec were apparent. Maybe on the copyright line, or as alt-text for the logo.

**Comment by marcoscaceres** [comment]
Should be trivial to add the version to the about page - that's a good suggestion. 

Please note that in the mean time, there is a "meta generator" tag+attribute that ReSpec adds when one creates a snapshot. That includes the ReSpec version... though it's a pain to find because it's in markup. Would like to keep that as the way we indicate the ReSpec version that was used to generate a document, however.

**Comment by halindrome** [comment]
I like the change.  Fix the travis nonsense and LGTM.

**Comment by marcoscaceres** [comment]
😢 Uglify2 can't handle ES6 yet. And without it, ReSpec blows up to 1.2Mb. I'll have to repackage it in pieces.  Also tried with Closure compiler, but also had no joy. 

Why is life so hard. WHY!

**Comment by marcoscaceres** [comment]
@patrickkettner, to build: 

```bash
git checkout async
./tools/build-w3c-common.js
```

The actual builder is "tools/builder.js"

**Comment by marcoscaceres** [comment]
@patrickkettner, you can test the output with: 

```Bash
npm run server
open http://localhost:8000/examples/basic.built.html
```

**Comment by patrickkettner** [comment]
```
➜  respec git:(async) ✗ ./tools/build-w3c-common.js

module.js:457
    throw err;
    ^

Error: Cannot find module 'temp'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/tmp/respec/tools/builder.js:8:30)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

```
$ npm install temp
```

```
$ ./tools/build-w3c-common.js

  ⏲  Generating respec-w3c-common.js. Please wait...
{ Error: Error: ENOENT: no such file or directory, open '/private/tmp/respec/js/deps/async.js'
    at Error (native)

    at /private/tmp/respec/node_modules/requirejs/bin/r.js:25865:19
    at /private/tmp/respec/node_modules/requirejs/bin/r.js:3056:39
    at /private/tmp/respec/node_modules/requirejs/bin/r.js:2996:25
    at Function.prim.nextTick (/private/tmp/respec/node_modules/requirejs/bin/r.js:25616:9)
    at Object.errback (/private/tmp/respec/node_modules/requirejs/bin/r.js:2995:26)
    at Object.callback (/private/tmp/respec/node_modules/requirejs/bin/r.js:2981:23)
    at Object.then (/private/tmp/respec/node_modules/requirejs/bin/r.js:3035:23)
    at build (/private/tmp/respec/node_modules/requirejs/bin/r.js:25822:12)
    at runBuild (/private/tmp/respec/node_modules/requirejs/bin/r.js:27831:17)
    at Object.execCb (/private/tmp/respec/node_modules/requirejs/bin/r.js:1943:33)
  originalError: 
   { Error: ENOENT: no such file or directory, open '/private/tmp/respec/js/deps/async.js'
       at Error (native)
       at Object.fs.openSync (fs.js:640:18)
       at Object.fs.readFileSync (fs.js:508:33)
       at Object.readFile (/private/tmp/respec/node_modules/requirejs/bin/r.js:3655:27)
       at Object.readFileAsync (/private/tmp/respec/node_modules/requirejs/bin/r.js:3669:32)
       at Function.require._cacheReadAsync (/private/tmp/respec/node_modules/requirejs/bin/r.js:25635:25)
       at /private/tmp/respec/node_modules/requirejs/bin/r.js:25205:48
       at /private/tmp/respec/node_modules/requirejs/bin/r.js:3038:37
       at /private/tmp/respec/node_modules/requirejs/bin/r.js:2986:25
       at Function.prim.nextTick (/private/tmp/respec/node_modules/requirejs/bin/r.js:25616:9)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/private/tmp/respec/js/deps/async.js',
     fileName: '/private/tmp/respec/js/deps/async.js' } }
```

**Comment by marcoscaceres** [comment]
@gkellogg, I added shipped your feature request... you can see it in ReSpec's about box now.

**Comment by marcoscaceres** [comment]
@patrickkettner, thanks again for your help with Uglify#harmony. 

It still had a few issues, but it helped a bit. Some limitations I ran into: 

 * fat arrow support is a bit spotty
 * doesn't seem to like variables that are not fully initialized, like `let x;`... unless they are `var`.
 * Template strings are not yet supported.
 * object short hands (e.g., `{foo(){}}`) not supported yet. 
 * argument defaults not supported yet.

**Comment by patrickkettner** [comment]
@marcoscaceres (sorry if I am being thick and missing something obvious, but...) is there anything I can do to help this along?

**Comment by marcoscaceres** [comment]
@patrickkettner, no, it's all good 😄 Just waiting for Edge 14 to drop with all the new goodies. Also, I realized that Uglify#harmony was actually doing the right thing, but that Yarn was grabbing the stable release.

**Comment by patrickkettner** [comment]
awesome, let me know if there is anything I can test if you don't want to download a insider build

cheers!

**Comment by marcoscaceres** [comment]
closing for now. Will continue cherry picking as features in browsers get released.

**Pull request closed without merging**
