### PR TITLE
Update npm dependencies

### PR DESCRIPTION
**Pull request by tripu**
&hellip;running [updtr](https://github.com/peerigon/updtr). (And sort the lines alphabetically.)

(`npm` complains that there is no licence information in `package.json`; I would have added it myself, but I don't know which licence this projects uses; it isn't said on the repo nor on [`w3.org/respec`](http://www.w3.org/respec/)&hellip;)

### CODE REVIEW

**Comment by plehegar** [comment]
LGTM

**Comment by marcoscaceres** [comment]
@dontcallmedom, if you have time, can you check out this branch and check that it doesn't break the phantom stuff? I'm not inclined to merge this until I have an OK from you.

**Comment by tripu** [comment]
Tests pass. What is &ldquo;the Phantom stuff&rdquo;? :)

**Comment by marcoscaceres** [comment]
The untested document generator, which relies on phantom.js... It breaks easily.

**Comment by tripu** [comment]
:+1:

**Pull request merged**
