### PR TITLE
test(core/markdown-spec): reenable custom id test

### PR DESCRIPTION
**Pull request by saschanaz**
Finally had time to figure it out. That part was reverted by #2678.

### CODE REVIEW

**Comment by saschanaz** [comment]
I wonder who uses the custom id feature, though?

**Comment by sidvishnoi** [comment]
> I wonder who uses the custom id feature, though?

No one yet (need to document it). But it's commonly used in Bikeshed specs, so we decided to support it.

**Comment by saschanaz** [comment]
> 
> 
> > I wonder who uses the custom id feature, though?
> 
> No one yet (need to document it). But it's commonly used in Bikeshed specs, so we decided to support it.

Was there a request or is it Marcos who wanted it?

**Comment by sidvishnoi** [comment]
Marcos wanted it.
We also want to work on markdown [definition lists](https://www.markdownguide.org/extended-syntax/#definition-lists), but that's a difficult one as marked.js is being tough.

**Comment by saschanaz** [comment]
Didn't even know markdown has a definition list syntax 😁

**Comment by sidvishnoi** [comment]
It's non standard syntax (as if markdown has a standard)

**Comment by saschanaz** [comment]
Markdown has a standard named CommonMark.

**Comment by sidvishnoi** [comment]
Good point. Forgot it. /me takes statement back.

**Pull request merged**
