### PR TITLE
Feat (base-runner.js): Adds document.respecIsReady promise (closes #607)

### LINKED ISSUE #607: Can we provide a Promise that will resolve when everything is really done?
One of the problems people have with extending ReSpec / providing other instrumentation is that we don't fire any sort of event that means "we are really really really done".  Is there a way to accomplish this with a Promise?  Or with a DOM event?

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@halindrome r?

**Comment by marcoscaceres** [comment]
Ok, we have a problem here. Phantomjs (that outdated piece of crap) doesn't support promises. They can only be polyfilled in. However, because this script requires Promises to be brought in extremely early, the Promises polyfill MUST run before RequireJS. That means that the example specs used by "./headless.js" all need to include the Promise.js polyfill. 

If we want this feature, it's time to retire "headless.js" once and for all.

**Comment by marcoscaceres** [comment]
This PR now retires headless.js.

**Comment by halindrome** [comment]
I have a meeting but will look this over shortly.

On Mon, Mar 7, 2016 at 8:28 AM, Marcos Caceres <notifications@github.com>
wrote:

> This PR now retires headless.js.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/pull/616#issuecomment-193271270>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
Bah, forgot about the spec generator thing used by the w3c. Will probably need to rollback removing headless.js and just late bind the promise via requirejs. I hate Phantomjs a little bit more everyday day.

**Comment by marcoscaceres** [comment]
.... Hmmm, maybe it's time to look at jsdom again.

**Comment by halindrome** [comment]
Funny that you forgot about it since THIS is the thing that we are blocking
with the jquery extension bug.

On Mon, Mar 7, 2016 at 9:56 AM, Marcos Caceres <notifications@github.com>
wrote:

> .... Hmmm, maybe it's time to look at jsdom again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/pull/616#issuecomment-193313178>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
> Funny that you forgot about it since THIS is the thing that we are blocking with the jquery extension bug.

Ah, I thought it was affecting some live specs.

**Comment by halindrome** [comment]
Those also.

**Comment by marcoscaceres** [comment]
Sending again.

**Pull request closed without merging**
