### PR TITLE
feat: dark mode

### PR DESCRIPTION
**Pull request by sidvishnoi**
Closes https://github.com/w3c/respec/issues/2651

Disabled by default. Set `respecConfig.darkMode = true` to enable. 

Please provide feedback if you enable dark mode. You can add `?darkMode=true` to your ReSpec spec URL and toggle dark mode in system/browser to preview without making editorial changes.

This gives a "good enough" support for dark mode. Not all styles are perfected yet.
And some styles can't be overridden by the manual theme toggle (they only respect `@media (prefers-color-scheme: dark) {...}`).
I've tried to use W3C stylesheets's CSS variables wherever possible to avoid this, but at least styles for code syntax highlighting (including WebIDL), and definition panel aren't supported in that theme, so they won't fully respect the manual theme toggle.

---

If you want to try dark mode before this gets merged (please do, to provide feedback), you can replace the `respec-w3c` script with `https://deploy-preview-3236--respec-pr.netlify.app/respec-w3c.js`:
```diff
- <script src='https://www.w3.org/Tools/respec/respec-w3c' class='remove'></script>
+ <script src='https://deploy-preview-3236--respec-pr.netlify.app/respec-w3c.js' class='remove'></script>
```
Or, use [ReSpec preview](https://respec-preview.netlify.app/?spec=https%3A%2F%2Fw3c.github.io%2Fpayment-request%2F&version=https%3A%2F%2Fdeploy-preview-3236--respec-pr.netlify.app%2Frespec-w3c.js&respecConfig=respecConfig.darkMode+%3D+true%3B) (NB: do a hard reload to override service worker there)

### CODE REVIEW

**Comment by saschanaz** [comment]
Do we know what happened to tr-design dark mode proposal?

**Comment by sidvishnoi** [comment]
> Do we know what happened to tr-design dark mode proposal?

https://github.com/w3c/tr-design/issues/241

**Comment by deniak** [comment]
The new stylesheet/js have been merged so it is now possible to enable the dark mode on the specifications by following https://www.w3.org/StyleSheets/TR/2016/README.html#dark

**Comment by deniak** [comment]
The dark mode stylesheet was deployed about 2 years ago and we had requests from people to add that feature. While editors could include the stylesheet themselves, it might be better to have an option to enable the dark mode which would simply include the stylesheet (https://www.w3.org/StyleSheets/TR/2016/README.html#dark) in the document.

**Comment by sidvishnoi** [comment]
Will add a test too😄

**Review by marcoscaceres — APPROVED** [review]
Looks great... the only thing we should fix as a followup is the MDN buttons... but otherwise, looks really good. 

The IDL boxes maybe too... they could probably be made a bit more "dark", but they look fine and will definitely do! 

Nice one @sidvishnoi

**Pull request merged**
