### PR TITLE
Revert "fix(core/markdown): use reindent() instead (#2650)"

### PR DESCRIPTION
**Pull request by marcoscaceres**
This reverts commit d33de51ec5100987ce3b6aef95888a3ab0c29fea.

@saschanaz, sorry, we had to revert this :( it turns out a lot of specs are depending on this behavior. We'll need to go through specs that use `format: "markdown"` and fix them manually (or find some other alternative) before we can again merge this.

### CODE REVIEW

**Comment by saschanaz** [comment]
Could you list the examples?

**Comment by marcoscaceres** [comment]
See:
 https://github.com/search?q=org%3Aw3c+format%3A+markdown&type=Code

And see:
 https://w3c.github.io/trace-interchange-format/

We fixed, then we realized lots broke:
 https://w3c.github.io/resource-hints/

**Comment by saschanaz** [comment]
I think the trace-interchange-format depends on `data-include` which conflicts with new indentation. Could we try fixing it?

**Comment by sidvishnoi** [comment]
Not just data-include-format=markdown. https://w3c.github.io/preload/ doesn't use it, still broken.

**Comment by marcoscaceres** [comment]
>  Could we try fixing it before reverting?

We can. You up for a late night marathon hacking session? :)

**Comment by saschanaz** [comment]
> Not just data-include-format=markdown. https://w3c.github.io/preload/ doesn't use it, still broken.

Indentation of `<pre>` looks broken there, probably written before ReSpec autoprocess them.

The search result Marcos gave shows a lot of specs depends on data-include, so fixing it probably significantly reduce the broken spec list. What do you think?

**Comment by marcoscaceres** [comment]
It's basically any spec that declares "markdown" and then has bad indentation, I think.

**Comment by saschanaz** [comment]
>probably written before ReSpec autoprocess them.

(I think HTML needs a native way to not require awkward indentations in `<pre>`... 🤔

**Comment by saschanaz** [comment]
>You up for a late night marathon hacking session? :)

Will try 😂

**Comment by sidvishnoi** [comment]
Another example without data-include-format=markdown : https://w3c.github.io/performance-timeline/
Indentation seems fine there (unless I missed something)

**Comment by marcoscaceres** [comment]
@saschanaz, I'll stay up for another hour (2am my time). Ping me on Slack if it's looking too broken. 

Otherwise, please ping @sidvishnoi and check how long he will be up for.

**Comment by sidvishnoi** [comment]
I've ~3 hours. Lets collect the broken specs, revert this commit (and release) (and sleep if needed), fix the specs using https://unpkg.com/respec@25.0.0/builds/respec-w3c.js, fix respec, release.

**Comment by saschanaz** [comment]
Got a title: Web breaker

**Comment by marcoscaceres** [comment]
When we come back to this:
 https://github.com/search?q=org%3AWICG+markdown&type=Code

**Pull request merged**
