### PR TITLE
refactor(core/informative): move W3C informative module to core incl l10n

### PR DESCRIPTION
**Pull request by thijsbrentjens**
As a result of discussion in https://github.com/w3c/respec/pull/2192, move the W3C informative module to core and add localization. For now only nl added to en.
 
I tried to follow your conventions, but please let me know if things need improvement.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Looks great. I'll set up test now.

**Comment by marcoscaceres** [comment]
Actually, will have to be tomorrow for the test. But looking good.

**Comment by thijsbrentjens** [comment]
Thanks. And no problem of course, you've already responded very fast.

**Comment by saschanaz** [comment]
That GitHub thing again fails? 🤔

**Comment by marcoscaceres** [comment]
Yep, we need #2197.

**Comment by saschanaz** [comment]
Last time we didn't change any tests. I think this may mean we are creating a more frequent API calls...

**Comment by marcoscaceres** [comment]
> Last time we didn't change any tests. I think this may mean we are creating more frequent API calls...

Because Travis' IP are all shared, a single call to GitHub can push it over the 60 calls limit (as someone else on the server might have consumed all the available calls)... in theory, once  #2197 goes in, it should not fail anymore... but if it does, then the original patch is doing bad things by making redundant network calls to github.

**Pull request merged**
