### PR TITLE
[WIP] feat(core/mdn-browser-compat): Include MDN browser compatibility data

### PR DESCRIPTION
**Pull request by himanish-star**
fixes: #1693
This is WIP, I have implemented this to work with all the [browser apis](https://github.com/mdn/browser-compat-data/tree/master/api). But haven't thought about other things like `CSS`, `HTML`, etc. present in the MDN browser compat data

You can try out my `basic.html` to see how I have integrated the data.

I have basically created a support table for each `method`/`attribute`. I am doing this by selecting appropriate `dfn` elements and appending next to them their respective compatibility data. However, as you can see in PaymentRequest API which has a `constructor` which is not encapsulated in a `dfn` tag. I have no idea how to select that.

So @marcoscaceres, do you like my way of implementing this? Or do you want me to represent all the data in a big table at one place like it has been done at https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest#Browser_compatibility?

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@himanish-star could you please post a screenshot or two so we can see how it's coming along?

**Comment by himanish-star** [comment]
sure :)

**Comment by himanish-star** [comment]
image

**Comment by himanish-star** [comment]
A video now:

ezgif com-crop

**Comment by marcoscaceres** [comment]
Ok, we need to see what's unique vs what's being put together in #2110, which will look like this:
https://github.com/w3c/respec/issues/1858#issue-372309961

**Comment by marcoscaceres** [comment]
Closing in favor of #2110

**Pull request closed without merging**
