### PR TITLE
Add a ready promise to ReSpec (closes #607)

### LINKED ISSUE #607: Can we provide a Promise that will resolve when everything is really done?
One of the problems people have with extending ReSpec / providing other instrumentation is that we don't fire any sort of event that means "we are really really really done".  Is there a way to accomplish this with a Promise?  Or with a DOM event?

### PR DESCRIPTION
**Pull request by marcoscaceres**
WIP patch. Need to add some tests.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@halindrome, wdyt?

**Comment by marcoscaceres** [comment]
basically, you can now ask:

```
document.respecIsReady.then(doStuff);
```

**Comment by halindrome** [comment]
I will take a look.  Is there a risk that respecIsReady won't be defined?
In otherwords, do I need to put that in an init block that fires on
DOMReady or something?

On Fri, Mar 4, 2016 at 2:44 AM, Marcos Caceres <notifications@github.com>
wrote:

> basically, you can now ask:
>
> document.respecIsReady.then(doStuff);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/pull/609#issuecomment-192186523>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
> On 5 Mar 2016, at 12:01 AM, Shane McCarron <notifications@github.com> wrote:
> 
> I will take a look. Is there a risk that respecIsReady won't be defined?

I put it to run sync way before onload. That also fixed the current problem that respectDone wax only bound late (after all plugins finished). 


> In otherwords, do I need to put that in an init block that fires on
> DOMReady or something?

No, that's way too late. Where it is right now is as early as possible.

**Comment by halindrome** [comment]
I asked the question wrong.  What I mean is "If I were to want to take advantage of this in a document that uses respec, either directly in the source file or in a JS file that was included, when would be the earliest that I could be confident I can bind to it?"

**Comment by marcoscaceres** [comment]
It will be there before anything else related to respec. It is literally one of the first things added (i.e., just after requirejs loads and before anything else).

**Comment by halindrome** [comment]
Got it - thanks.  I will play with it later today.

On Fri, Mar 4, 2016 at 9:48 AM, Marcos Caceres <notifications@github.com>
wrote:

> It will be there before anything else related to respec. It is literally
> one of the first things added (i.e., just after requirejs loads and before
> anything else).
>
> Sent from my iPhone
>
> > On 5 Mar 2016, at 2:08 AM, Shane McCarron <notifications@github.com>
> wrote:
> >
> > I asked the question wrong. What I mean is "If I were to want to take
> advantage of this in a document that uses respec, either directly in the
> source file or in a JS file that was included, when would be the earliest
> that I could be confident I can bind to it?"
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/pull/609#issuecomment-192329445>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
Reworked this. Will send new PR.

**Pull request closed without merging**
