### PR TITLE
Fix(markdown): Space before quote (closes #786)

### LINKED ISSUE #786: Space appearing when quote is followed by element.
A [bug in jsbeautifier](https://github.com/beautify-web/js-beautify/issues/943) is affecting ReSpec.

Given HTML:

```HTML 
<p>If the document&#39;s origin is an opaque origin, throw a
&quot;<code>SecurityError</code>&quot; <code>DOMException</code>.</p>
```

jsbeautifier produces:

```HTML
<p>If the document&#39;s origin is an opaque origin, throw a &quot;
    <code>SecurityError</code>&quot; <code>DOMException</code>.</p>
```

Which results in a space between the quote and SecurityError, like: <samp> " <code>SecurityError</code>"
 
Expected: "<code>SecurityError</code>" with no spaces.

### PR DESCRIPTION
**Pull request by marcoscaceres**
Forgot to deal with spaces 👍 Serves me right for not adding test cases.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/respec/787)

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@dontcallmedom, if you have another sec. This adds literally two characters :)

**Comment by dontcallmedom** [comment]
Well, shouldn't you add test cases? >:)

**Comment by marcoscaceres** [comment]
I should, but it's 11pm here so will do it tomorrow

**Comment by marcoscaceres** [comment]
Added tests...

**Pull request merged**
