### PR TITLE
Modernize respec

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Ok, cleaned up history. This is more or less ready to go. There are a few nits that I can fix after merge. 

If anyone is inclined to do a review, it would be appreciated. However, this was a massive overhaul of ReSpec to modernize all the libraries, etc. and to limit our dependency on Phantomjs... hence, it's a crap-load of changes... and can understand if it's too much for anyone. 

Unfortunately, these changes could only be done in one go, as Jasmine 2.4 is not compatible with 1.2, and hence all the tests had to be rewritten. Also, there was just a lot of cruft that really needed to go or get fixed.

**Comment by halindrome** [comment]
I will have a troll.  My only initial comment is 2 spaces for indent?
 really?  I live in vim.... I will need to make some rule for vim or I am
going to mess it up for sure!

On Tue, Mar 1, 2016 at 7:21 AM, Marcos Caceres <notifications@github.com>
wrote:

> Ok, cleaned up history. This is more or less ready to go. There are a few
> nits that I can fix after merge.
>
> If anyone is inclined to do a review, it would be appreciated. However,
> this was a massive overhaul of ReSpec to modernize all the libraries, etc.
> and to limit our dependency on Phantomjs... hence, it's a crap-load of
> changes... and can understand if it's too much for anyone.
>
> Unfortunately, these changes could only be done in one go, as Jasmine 2.4
> is not compatible with 1.2, and hence all the tests had to be rewritten.
> Also, there was just a lot of cruft that really needed to go or get fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/pull/580#issuecomment-190722289>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
@halindrome, I can add an auto beautifier. Does vim support `.editorconfig` files?

**Comment by marcoscaceres** [comment]
@halindrome, I added defaulting to 2016 as the last commit set.

**Comment by marcoscaceres** [comment]
... once this is merged, we will get 2016 style support :dancer: :tada: :beers: and :pig2: ... because :pig: is awesome.

**Comment by halindrome** [comment]
I thought style support was in a different PR?

On Tue, Mar 1, 2016 at 8:38 AM, Marcos Caceres <notifications@github.com>
wrote:

> ... once this is merged, we will get 2016 style support [image: :dancer:] [image:
> :tada:] [image: :beers:] and [image: :pig2:] ... because [image: :pig:]
> is awesome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/pull/580#issuecomment-190745400>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by halindrome** [comment]
Oh, and yes - vim has editorconfig support.  Thank you!

On Tue, Mar 1, 2016 at 9:17 AM, Shane McCarron <halindrome@gmail.com> wrote:

> I thought style support was in a different PR?
>
> On Tue, Mar 1, 2016 at 8:38 AM, Marcos Caceres <notifications@github.com>
> wrote:
>
>> ... once this is merged, we will get 2016 style support [image: :dancer:] [image:
>> :tada:] [image: :beers:] and [image: :pig2:] ... because [image: :pig:]
>> is awesome.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/w3c/respec/pull/580#issuecomment-190745400>.
>>
>
>
>
> --
> Shane McCarron
> halindrome@gmail.com
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by halindrome** [comment]
This branch seems to have introduced a dependency on a newer version of c++
than I have on my production servers.  I would bet that I am not alone in
this.  I will see if I can upgrade, but my point is that we may have a
maintenance problem for others.

On Tue, Mar 1, 2016 at 9:20 AM, Shane McCarron <halindrome@gmail.com> wrote:

> Oh, and yes - vim has editorconfig support.  Thank you!
>
> On Tue, Mar 1, 2016 at 9:17 AM, Shane McCarron <halindrome@gmail.com>
> wrote:
>
>> I thought style support was in a different PR?
>>
>> On Tue, Mar 1, 2016 at 8:38 AM, Marcos Caceres <notifications@github.com>
>> wrote:
>>
>>> ... once this is merged, we will get 2016 style support [image:
>>> :dancer:] [image: :tada:] [image: :beers:] and [image: :pig2:] ...
>>> because [image: :pig:] is awesome.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/w3c/respec/pull/580#issuecomment-190745400>.
>>>
>>
>>
>>
>> --
>> Shane McCarron
>> halindrome@gmail.com
>>
>
>
>
> --
> Shane McCarron
> halindrome@gmail.com
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by marcoscaceres** [comment]
> On 2 Mar 2016, at 2:17 AM, Shane McCarron <notifications@github.com> wrote:
> 
> I thought style support was in a different PR?

That got merged, but not shipped.

**Comment by marcoscaceres** [comment]
Maybe, but it's mostly you and I doing maintenance these days. However, we can add more help in the CONTRIBUTOR.md if needed.

**Pull request merged**
