### PR TITLE
Allow additional logo in CG spec

### PR DESCRIPTION
**Pull request by nickevansuk**
Allow for additional logos in the CG spec template

---

This change is [Reviewable](https://reviewable.io/reviews/w3c/respec/821)

### CODE REVIEW

**Comment by halindrome** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[js/w3c/templates/cgbg-headers.html, line 5 \[r1\]](https://reviewable.io:443/reviews/w3c/respec/821#-KJpM3iHbWojV7MeasjP:-KJpM3iHbWojV7MeasjQ:-915253184) ([raw file](https://github.com/w3c/respec/blob/fe7027f3affc6c7e9d25e9b99798973bc41aa392/js/w3c/templates/cgbg-headers.html#L5)):*
> ```HTML
>     <a class='logo' href='http://www.w3.org/'>W3C</a>
>   </p>
>   <p>
> ```

The showLogos function embeds the logos in a p element already.  I don't think you need the P in here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/respec/821)*

**Comment by marcoscaceres** [comment]
Please be sure to add a test or two. Let me know if you need a hand or anything.

**Comment by nickevansuk** [comment]
Have fixed <p> tag situation @halindrome, thanks. @marcoscaceres considering this feature exists on other templates, where would you advise adding a test?

**Comment by marcoscaceres** [comment]
@nickevansuk, looks like tests/spec/w3c/headers-spec.js would be the right place to add a test. It would just be a simple like:

```js
  it("adds multiple logos to CG spec", function(done) {
    var ops = makeStandardOps();
    var newProps = {
       specSatus: "CG", 
       logos: [{}, {}]
    };
    Object.assign(ops.config, newProps);
    makeRSDoc(ops, function(doc) {
      // Find the logos
      // Please avoid using jQuery here - we are trying to stop relying on it 
    }).then(done);
  });
```

**Comment by marcoscaceres** [comment]
@nickevansuk, in the test above, you want to check against both `specStatus` "CG-DRAFT", and "CG-FINAL" . You can get the logo code from the [logos example](https://github.com/w3c/respec/wiki/logos#example) in our Wiki.

**Comment by marcoscaceres** [comment]
I'll add tests for this locally, but the change is tiny and just reuses existing infra.

**Pull request merged**
