### PR TITLE
re-reverting to labs.w3.org

### PR DESCRIPTION
**Pull request by dontcallmedom**
for #314 sake

### CODE REVIEW

**Comment by darobin** [comment]
Does someone mind making a release?

**Comment by darobin** [comment]
@dontcallmedom actually, you have the release keys right?

**Comment by dontcallmedom** [comment]
I don't

**Comment by dontcallmedom** [comment]
I don't

**Comment by marcoscaceres** [comment]
I can release. Will do that in a bit.

**Comment by marcoscaceres** [comment]
done.

**Pull request merged**
