### PR TITLE
chore(package): don't snyk during prepare

### PR DESCRIPTION
**Pull request by marcoscaceres**
Snyk is completely broken at the moment. It's good to run snyk during build, but running it during prepare is 🤷‍♂️.

### CODE REVIEW

**Comment by saschanaz** [comment]
I think that line is previously intentionally added by the snyk bot... BTW, #2104 passed the test, what's the problem?

**Comment by marcoscaceres** [comment]
> BTW, #2104 passed the test, what's the problem?

I had to restart it a few times to get it to pass. The problem appear to be that it intermittently fails (like 50% on every stage). I've been restarting all the failing stages manually to get them to pass... but it's getting a little old.

**Comment by marcoscaceres** [comment]
I think what may be happening is that snyk is corrupting the cache on TravisCI when it does the fixes. I think it's doing the patches, then it gets confused because it can't find things that its patched.

**Comment by saschanaz** [comment]
#1413 and #1420 added the hook to run snyk, maybe removing it would trigger a new PR by snyk-bot to restore, but not sure.

**Comment by marcoscaceres** [comment]
I think we can add back to prepare again soon (and it runs at build time, so I'm ok with the current state of things)... but right now it's just too broken. Other option is disabling the cache on TravisCI, but that also slows us down.

**Pull request merged**
