### PR TITLE
refactor(tools/release): no need to checkout

### PR DESCRIPTION
**Pull request by saschanaz**
These lines does nothing, as the generated builds are already committed.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Oh, um... maybe then we should run these earlier? Like right at the start?

**Comment by saschanaz** [comment]
> Oh, um... maybe then we should run these earlier? Like right at the start?

What would be the purpose, when we do want to commit the builds?

**Comment by marcoscaceres** [comment]
> What would be the purpose, when we do want to commit the builds?

When running `npm start`, the developer server constantly regenerates builds/... once someone finishes coding, stuff gets merged, etc. there might still be "dirty/outdated" builds/ files. The idea was to make sure those build files got removed... but maybe you are right... maybe the release script will complain early that there uncommitted files in "develop". I think we were trying to not bother ourselves with the build files, and just wanted them blown away.

**Comment by sidvishnoi** [comment]
FWIW, the `npm start` script undoes changes to `./builds/` on exit.
https://github.com/w3c/respec/blob/264cc6fffcc088a6223141d6124e63c150238f67/tools/dev-server.js#L87-L89

**Comment by saschanaz** [comment]
This is about `tools/release`, not `npm start`. Releasing should regenerate and commit the builds, so there shouldn't be "dirty" one here.

**Comment by marcoscaceres** [comment]
Right, I need to check 🥴. I know these is about release, but `npm start` is the dev workflow that leads to release. So the thing to check is if possible to release after running `npm start`,

**Pull request merged**
