### PR TITLE
bundled starter page

### PR DESCRIPTION
**Pull request by nileshgulia1**
Bundled starter page,Can we use parcel's dev server instead of `http server`.

### CODE REVIEW

**Comment by saschanaz** [comment]
What's the merit when we do this?

**Comment by marcoscaceres** [comment]
Agree, would be great to hear a little more as I’ve never used parcel.

**Comment by nileshgulia1** [comment]
Actually, parcel doesn't need a configuration file like webpack, we just point it to a single file and let it do the magic, I thought it will be good if we start with `starter` page or `basic .html` which will be good for the contributers in future.

**Comment by saschanaz** [comment]
1. It seems parcel uses `uglify-es@^3.2.1` which includes `3.3.9` that caused https://github.com/w3c/respec/issues/1458.
2. Using parcel probably means we don't have to directly depend on uglify. Can you modify `tools/builder.js` to use parcel instead of babel+uglify?

**Comment by nileshgulia1** [comment]
@saschanaz  I have removed `Uglify.js` package and make parcel to build `builder.js` file.

**Comment by saschanaz** [comment]
(Note that Travis test won't run until the conflicts are resolved)

**Comment by nileshgulia1** [comment]
@saschanaz  Done!

**Comment by nileshgulia1** [comment]
@saschanaz  I don't know why travis is failing, while my local `npm run build` commands are executing perfectly.

**Comment by saschanaz** [comment]
It seems `npm run parcel` is what failing now.

**Comment by nileshgulia1** [comment]
Thanks a lot @saschanaz ;)

**Comment by marcoscaceres** [comment]
Seems this needs a rebase... there are also a bunch of cache files that probably should not be there?

**Comment by saschanaz** [comment]
Also, probably the target shouldn't be `builder.js` as it's just a builder script, not an actual library. And the result should be in `builds/`, not in `dist/`.

**Comment by nileshgulia1** [comment]
>Also, probably the target shouldn't be builder.js as it's just a builder script

@saschanaz   Parcel does not support multiple entry points like webpack. I guess there should be one main entry point and parcel should bundle these files to the specified directory.

**Comment by saschanaz** [comment]
Currently the entry point is `/js/profile-w3c-common.js`, as you can see in `examples/basic.html`:

https://github.com/w3c/respec/blob/cab4974fcab6cb564533a4ccce46ce79debb2970/examples/basic.html#L6-L7

**Pull request closed without merging**
