### PR TITLE
l10n(w3c/templates/headers): updated Japanese translations

### PR DESCRIPTION
**Pull request by himorin**
updated Japanese section to align with the current English lines.

### CODE REVIEW

**Comment by xfq** [comment]
(as a reminder, we should sync the changes to [jlreq](https://github.com/w3c/jlreq/blob/0d75d018a9fa9041231550fc7d98cbc47a8f8a7f/script.js#L23) as well.)

**Review by marcoscaceres — APPROVED** [review]

**Comment by himorin** [comment]
will update test files shortly.

@xfq yes, would want to update after https://github.com/w3c/jlreq/pull/264

**Comment by marcoscaceres** [comment]
@himorin, @xfq, let me know when you want me to merge + release.

**Comment by himorin** [comment]
oh! I thought test failure was from missing update on test(s). 
it seems it's not, so I am happy with this to be merged.

**Pull request merged**
