### PR TITLE
fix(core/dfn-finder): dfn-for should not be lcased

### LINKED ISSUE #2483: Exports should retain case
When IDL exporting definitions, the definitions should retain the same case form. Right now, we are exporting everything as lower case.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #2483

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Darn... the stupid/legacy lower casing search stuff strikes again. I think we finally need to kill lower case stuff of IDL lookups.

**Comment by marcoscaceres** [comment]
It's a big job, so I'll have to come back to this after web share.... But we this is high priority, as all our exports are to Shepherd are currently wrong.

**Comment by saschanaz** [comment]
Oh, I assume the bikeshed people are angry 😨

**Comment by marcoscaceres** [comment]
Not yet... but they will be.

**Comment by marcoscaceres** [comment]
@saschanaz do you see some sane way of doing this? I tried a bunch of different things but just ended breaking it 😢

**Comment by saschanaz** [comment]
Hmmm I'll look into it

**Comment by saschanaz** [comment]
Fixed tests except the "uniquely links to enum values" test. That thing has been already broken because:

* The previous behavior was to insert `data-dfn-for="test2"` to `<dfn>`s without `data-dfn-for` when a parent has `data-dfn-for="Test2"`, __without lowercasing the parent's attribute__.
* Then the definition finder tries to find the definition for `Test2["enum"]` with `closest('[data-dfn-for="test2"]')`.
* It somehow worked because only one `<dfn>` had `data-dfn-for="test2"` while the common parent had `data-dfn-for="Test2"`
* Now it fails, the finder now does `closest('[data-dfn-for="Test2"]')`.

**Comment by saschanaz** [comment]
Okay, tests pass. We should probably mark this as a breaking change because things are now case sensitive.

**Comment by marcoscaceres** [comment]
Woah, you are the best! 🙇

**Comment by saschanaz** [comment]
@sidvishnoi @marcoscaceres The issue continues. Could you please check whether the repo settings page includes something relevant?

**Comment by marcoscaceres** [comment]
Ok, should be good now 🙂

**Comment by saschanaz** [comment]
@marcoscaceres Great! What was it?

**Comment by marcoscaceres** [comment]
I’d checked too many options in the branch protection section. I unchecked the ones that were stuck. I also gave you both admin access if we need change anything.

**Pull request merged**
