### PR TITLE
fix(assets/datatype): use CSS defaults for vars

### PR DESCRIPTION
**Pull request by marcoscaceres**
https://github.com/w3c/webdriver/issues/1424

### CODE REVIEW

**Comment by saschanaz** [comment]
I think those properties are for typed variables. Are we sure they won't be broken with this change?

**Comment by marcoscaceres** [comment]
Ah, let me try... I only tried clicking on them but not the hover.

**Comment by fantasai** [comment]
So Firefox definitely has a bug here where it leaves behind an empty piece of inline box on the first line if the var gets pushed to the second. But Chrome seems to render OK as long as you keep the 'position: relative'.

**Comment by fantasai** [comment]
(I will note that the tooltip goes offscreen when it's long and the var is short and you're near the start or end of the window. But fixing that is a different problem.)

**Comment by marcoscaceres** [comment]
Ok, I think this addresses the reported bug at least... @fantasai is right that there is definitely a lot of work to do on this.

**Comment by marcoscaceres** [comment]
> So Firefox definitely has a bug here where it leaves behind an empty piece of inline box on the first line if the var gets pushed to the second. 

Filed #2367 to track that... still seeing some weirdness in Chrome.

**Pull request merged**
