### PR TITLE
fix(assets/respec.css): prevent splitting title in issue-summary with single item

### PR DESCRIPTION
**Pull request by sidvishnoi**
Fixes https://github.com/w3c/respec/issues/3135

| Before | After |
| -- | -- |
| image | image |

Works fine with multiple issues also: image

### CODE REVIEW

**Comment by saschanaz** [comment]
So are we workarounding a CSS implementation error? If then I prefer adding a comment possibly with links to browser bugs.

**Comment by sidvishnoi** [comment]
Not sure if it's an implementation error. I couldn't find any relevant browser bugs.
Looks like this is how multi-column works. I'll read the spec to confirm.

**Comment by marcoscaceres** [comment]
I think @sidvishnoi fix is correct, in as far as each issue should be treated as a self contained unit. What multi-col would be correct for a run of text. Having said that, the proper fix here would be for us to use CSS grid (for the same reason I mentioned... each "issue" is actually self contained block of information).

**Review by marcoscaceres — APPROVED** [review]
I can live with this... or better would be CSS Grid to solve this.

**Comment by saschanaz** [comment]
If every browser is showing the same behavior I think we can just proceed.

**Comment by sidvishnoi** [comment]
One difference with grid comes when titles have uneven length (multi-column behaves as masonry layout, grid keeps equal height). Not sure which one we prefer.
| Grid | Multicol |
| -- | -- |
| image | image |

**Comment by saschanaz** [comment]
I think multicol is better here, as we don't need the empty space.

**Comment by andrea-perego** [comment]
Thanks, @sidvishnoi

**Pull request merged**
