### PR TITLE
chore: deprecate respecIsReady in favor of respec.ready

### PR DESCRIPTION
**Pull request by sidvishnoi**
- Do not yet remove `document.respecIsReady`, mark as deprecated only.
- BREAKING CHANGE: `respecIsReady` no longer resolves with `respecConfig`.
- Replace all usage of `respecIsReady` with `respec.ready`.
- Support `respecIsReady` fallback in `respecDocWriter` for backward compat.

Part of https://github.com/w3c/respec/issues/3089. Also see https://github.com/w3c/respec/pull/3082#discussion_r475473908

### CODE REVIEW

**Comment by sidvishnoi** [comment]
Only remaining occurrences of `respecIsReady`:
image

**Review by marcoscaceres — APPROVED** [review]

**Review by saschanaz — APPROVED** [review]
I'm late but 👍

**Comment by sidvishnoi** [comment]
I wonder if we should mark is as breaking change. Based on my GitHub search, I didn't find anyone using the resolved `respecConfig` from `document.respecIsReady`, which is the only breaking change in this PR.

**Comment by marcoscaceres** [comment]
Up to you - but this seems pretty safe to merge.

**Comment by saschanaz** [comment]
IMO a breaking change is a breaking change, even when seemingly there is no real use anymore. But up to you, yes.

**Comment by sidvishnoi** [comment]
Lets merge this as non-breaking :crossed_fingers:

**Pull request merged**
