### PR TITLE
perf(core/xref): get query id in parallel

### PR DESCRIPTION
**Pull request by sidvishnoi**
Haven't measured, but gotta be faster?

### CODE REVIEW

**Comment by sidvishnoi** [comment]
It's fast as in takes less time, but maybe not better. Tested on ~11k items. Left is for loop (older), right is Promise.all (newer).

No CPU throttling:
image

at 4x slowdown:
image

**Comment by sidvishnoi** [comment]
The slowest part is `{id, ...entry}` btw 😄

**Comment by marcoscaceres** [comment]
@sidvishnoi, when you are around, let me know what you want to do with this?

**Comment by sidvishnoi** [comment]
Closing as it has no major benefit. From the Chrome Devtools Performance Panel, `Promise.all` on many `objectHash` calls blocks the main thread (though only with really large number of calls). Might be beneficial to limit the "max concurrency", but meh. Will send a PR to reduce the `{id, ...entry}` overhead though.

**Pull request closed without merging**
