### PR TITLE
Changed .hljs-comment color

### PR DESCRIPTION
**Pull request by Nikhar444**
Fix for #2737

### CODE REVIEW

**Comment by saschanaz** [comment]
It indeed does have better contrast, but now it's less distinguishable from normal black text. @sidvishnoi thoughts?

**Comment by sidvishnoi** [comment]
It's slightly less distinguishable, but I think as we've italics, we're good to go.

**Comment by Nikhar444** [comment]
> 
> 
> The new color has much better contrast, thanks!
> 
> Do you mind also adjusting hljs-string?

Thanks
I guess, hljs-string has good enough contrast.

**Comment by saschanaz** [comment]
>hljs-string has good enough contrast.

It also doesn't pass WCAG contrast though:

image

**Comment by Nikhar444** [comment]
@saschanaz @marcoscaceres  Please merge these changes in develop branch.

**Comment by sidvishnoi** [comment]
I found `#0d8601` to be slightly more vibrant than `#42803C`, while still satisfying AA.

**Comment by saschanaz** [comment]
> I found `#0d8601` to be slightly more vibrant than `#42803C`, while still satisfying AA.

Agreed, while it weirdly gets less contrast number (4.57 versus 4.53).

**Comment by marcoscaceres** [comment]
I'm merging this for now and we can fiddle with the color further as needed. Appreciate you doing this @Nikhar444!

**Comment by marcoscaceres** [comment]
@Nikhar444, could you be a super hero and make the same changes to:
https://github.com/highlightjs/highlight.js/blob/master/src/styles/atom-one-light.css

We are just using that one, so we might as well also fix it for everyone at the source.

**Comment by Nikhar444** [comment]
> 
> 
> @Nikhar444, could you be a super hero and make the same changes to:
> https://github.com/highlightjs/highlight.js/blob/master/src/styles/atom-one-light.css
> 
> We are just using that one, so we might as well also fix it for everyone at the source.

Sure @marcoscaceres, I'll make the changes there as well.

**Pull request merged**
