### PR TITLE
fix(core/data-cite): clean up before save only

### PR DESCRIPTION
**Pull request by sidvishnoi**
- We can `data-cite` in later plugins now (will be needed in external dependency list)
- Also, xref to clean up after itself

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Hmm... I think we should probably not do the cleanup (and remove the cleanup from `core/data-cite.js`). Otherwise, it makes it really hard to debug things when things go wrong.

**Comment by sidvishnoi** [comment]
We should probably do better cleanup before export though

**Comment by marcoscaceres** [comment]
> We should probably do better cleanup before export though

Good idea! We could run it on save!

**Comment by marcoscaceres** [comment]
What might be better is that each module has its own cleanup listener tho. Otherwise centralizing everything is a bit messy.

**Comment by marcoscaceres** [comment]
(breaking tests aside, lol)

**Pull request merged**
