### PR TITLE
Fixed needing double def of term when data-lt is used (closes #470)

### LINKED ISSUE #470: Double definition of term when data-lt is used
when using `data-lt`, ReSpec should grab the text content from the <dfn> and use that as the first item in the `data-lt. Otherwise, you end up with,  E.g.,:

```HTML
<dfn data-lt="installed|installing">installed</dfn>
```

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Just noticed there was already a `normalizeString` equiv. called `norm`.

**Comment by marcoscaceres** [comment]
* added additional test for when dfn is normalized to the empty string
* removed use of `.startsWith()` as apparently PhantomJS that runs on TravisCI is still in the dark ages?

**Comment by darobin** [comment]
@marcoscaceres PhantomJS is pretty much always in the dark ages...

**Comment by marcoscaceres** [comment]
Maybe in a year or so we can move to https://slimerjs.org/  ... though I see they are also behind :( this is why we can't have nice things.

**Comment by darobin** [comment]
We should give jsdom a new shot now that they've fixed their performance issues with ReSpec. Also, I'm told Phantom 2 is actually getting decent(er).

**Pull request merged**
