### PR TITLE
Feat(utils): add makeOwnerSwapper()

### PR DESCRIPTION
**Pull request by marcoscaceres**
Utility function that allows swapping a Node from one document to another. Useful for various incoming improvements.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
r please?

**Comment by marcoscaceres** [comment]
Merging, as it's causing me bit-rot and can't proceed without it. Would still appreciate a once over.

**Comment by halindrome** [comment]
Sorry, I have been heads down parenting for a week or so.  Question: do you know the level of support for adoptNode.  I had not seen it before, and the DOM Recommendation has text about what to do if it is not supported (which, I suppose, we could just do.  It seems simple enough).

**Comment by marcoscaceres** [comment]
> On 18 May 2016, at 10:45 PM, Shane McCarron <notifications@github.com> wrote:
> 
> Sorry, I have been heads down parenting for a week or so. Question: do you know the level of support for adoptNode.
> 

It's a pretty ancient API (like late 1990s), so will be well supported. At least, not had any problems in the browsers on my machine. It's been in Firefox since version 3. 

> I had not seen it before, and the DOM Recommendation has text about what to do if it is not supported (which, I suppose, we could just do. It seems simple enough).
> 
The importNode() stuff? It's probably not needed, tbh. At least, I haven't had any issues as the sub documents we create are all spawned from the same document.

**Comment by halindrome** [comment]
Excellent.  Thanks

**Pull request merged**
