### PR TITLE
Remove ye olde idl

### PR DESCRIPTION
**Pull request by marcoscaceres**
Need to fix the following specs first: 

 * [x] https://github.com/w3c/clipboard-apis/issues/31
 * [x] https://github.com/WebAudio/web-midi-api/issues/170
 * [x] https://github.com/w3c/pointerlock/issues/13
 * [x] https://github.com/w3c/push-api/issues/216
 * [x] https://github.com/w3c/quota-api/issues/6
 * [x] https://github.com/w3c/selection-api/issues/76
 * [x] https://github.com/WebAudio/web-audio-api/issues/833
 * [x] Client Hints 
 * [x] Resource timing spec

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Quick update. Happy to report that the following specs have all been migrated (or a being migrated) to new school IDL:

* Clipboard APIs
* Web MIDI API
* Pointerlock
* Push API
* Quota API
* Selection API
* Resource Hints
* Timing spec

The Web Audio spec is using a particular version of ReSpec already, so it's not affected. 

With the above done, I feed confident that we can now push forward.

**Comment by marcoscaceres** [comment]
So, this works but current chrome canary is busted causing Karma to fail. However, the tests all pass.

**Comment by foolip** [comment]
@marcoscaceres, I found another:
https://www.w3.org/2011/tracking-protection/drafts/tracking-dnt.html

**Comment by marcoscaceres** [comment]
Argh... I see their new specs are also screwy. I tried tracking that spec down, but couldn't find it. 

@wseltzer, see above - ReSpec is kinda being used incorrectly by the specs... including the DNT with Promises spec.

**Comment by wseltzer** [comment]
@bert-github, can you make sure Roy sees the ping to TPWG?

**Pull request merged**
