### PR TITLE
Use www.w3.org for experimental style sheets

### PR DESCRIPTION
**Pull request by plehegar**
Should replace https://github.com/w3c/respec/pull/528

@halindrome @marcoscaceres @tripu

### CODE REVIEW

**Comment by plehegar** [comment]
See also https://github.com/w3c/respec/issues/520

**Comment by halindrome** [comment]
LGTM - want me to push an update?

**Comment by plehegar** [comment]
@halindrome yes please

**Comment by marcoscaceres** [comment]
Don't you need "://" on the front of that?

**Comment by marcoscaceres** [comment]
I mean just "//"

**Pull request merged**
