### PR TITLE
refactor(test/core/xref-spec)

### PR DESCRIPTION
**Pull request by ridhishjain**
issue #2438 
`"shows error if external term doesn't exist"`
this test is merged into 
`"adds link to unique external terms and shows error if external term doesn't exist"`

Do we need the file to be refactored in this manner?

### CODE REVIEW

**Comment by saschanaz** [comment]
Tests are intentionally granular even when it requires longer code, because granular tests allows maintainers to easily get where exactly is broken. So... IMO this change is not needed.

**Comment by ridhishjain** [comment]
In that case, can u tell me where exactly do we need refactoring?

**Comment by saschanaz** [comment]
I have no idea for now, @sidvishnoi do you have any?

**Comment by sidvishnoi** [comment]
> Tests are intentionally granular even when it requires longer code, because granular tests allows maintainers to easily get where exactly is broken. So... IMO this change is not needed.

This made introspect. I agree, we don't need these changes.
Earlier, I was thinking that we can merge some tests to improve testing speed, maintainability and reduce xref requests on server.

**Comment by ridhishjain** [comment]
then should I close this PR?

**Pull request closed without merging**
