### PR TITLE
Make jquery-enhanced get used in right places places

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@halindrome, this should fix #597. Please review.

**Comment by halindrome** [comment]
This does not appear fixed to me.  Use case: data-include is used to bring in an external file.  data-oninclude is used to transform the content of that file.  The function called uses jQuery constructs and the functions in core/jquery-enhanced are not available.  Not sure what I am missing.  If you want an example try http://pandora.aptest.com/w3c/aria-current/aria/aria.html - It references a version of respec that is built using this branch.

**Comment by marcoscaceres** [comment]
The simplest solution is just to include jquery-enhanced everywhere.

**Comment by marcoscaceres** [comment]
Will do that now.

**Comment by halindrome** [comment]
Just checking - do you think this is working now??

**Comment by marcoscaceres** [comment]
Not yet. Hopefully Monday. Found some other broken things that are blocking this one.

**Comment by marcoscaceres** [comment]
Ok, I think this is working... but need to break it up into smaller commits.

**Comment by marcoscaceres** [comment]
Today was a sad day - I swear i had it working and then it blew up. Getting close tho.

**Comment by marcoscaceres** [comment]
Ok, going to see what can be salvaged from here.... closing this PR, as #623 now includes at lot of this.

**Pull request closed without merging**
