### PR TITLE
fix(tools/respecDocWriter): output data, not dataURL

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Hotfix, as we accidentally broke the spec-generator.

**Comment by sidvishnoi** [comment]
Travis seems stuck. Restart? 
Code seems good but maybe we should wait for Travis checks

**Comment by marcoscaceres** [comment]
> Travis seems stuck. Restart?

It's queued... can take a while. However, it's 1am here, so I'm going to merge and release.

**Comment by marcoscaceres** [comment]
+ respec@20.10.1 

All is good in the world again 😇

**Pull request merged**
