### PR TITLE
fix(tools/respec2html): resolve src to file URL

### PR DESCRIPTION
**Pull request by marcoscaceres**
* relates to #1522

### CODE REVIEW

**Comment by marcoscaceres** [comment]
This doesn't fix the issue, but at least we get always get a URL based off file... it it's absolute URL, it just resolves as normal.

**Comment by saschanaz** [comment]
We already have `express` (and `http-server` for dev) dependency. Should we automatically open a local server until the Chrome issue gets fixed?

**Comment by marcoscaceres** [comment]
@saschanaz, we could... could you give me a rough sketch of how it might work?

**Comment by marcoscaceres** [comment]
Going to use this for now, as it technically correct. We can discuss a longer term solution separately.

**Pull request merged**
