### PR TITLE
chore(ci): use npm ci instead of npm i

### PR DESCRIPTION
**Pull request by sidvishnoi**
As we have a package-lock, we can use it, and it's faster than `npm install`.

### CODE REVIEW

**Comment by sidvishnoi** [comment]
Thanks to puppeteer being hostile to npm cache, we don't get benefits of this change.

**Comment by marcoscaceres** [comment]
I wonder if this will change in the future. I guess we can always revisit.

**Comment by sidvishnoi** [comment]
We longer install puppeteer in CI, so this can come back in :tada:

**Comment by sidvishnoi** [comment]
Oops. `npm ci` clears `node_modules` so our present cache is useless :laughing: 
Will add cache for `~/.npm` instead, to see if we get improvements.

**Comment by marcoscaceres** [comment]
sounds good

**Pull request merged**
