### PR TITLE
Fix maplike errors.

### PR DESCRIPTION
**Pull request by yutakahirano**
Reported in #361.
- There were HTML markup errors.
- Auto-generated method description was wrong.

### CODE REVIEW

**Comment by yutakahirano** [comment]
@ddorwin Can you take a look at the change?

**Comment by yutakahirano** [comment]
You can see the test output by [running a server] (https://github.com/w3c/respec/blob/develop/README.md#running-the-test-suite-in-a-browser).

**Comment by marcoscaceres** [comment]
FWIW, lgtm

**Comment by yutakahirano** [comment]
Thank you.

**Pull request merged**
