### PR TITLE
fix(w3c): switch to W3C, Inc.'s copyright

### PR DESCRIPTION
**Pull request by deniak**
Starting from January 1, 2023, TR documents should mention the new W3C Inc copyright.
See https://github.com/w3c/specberus/issues/1681

**To be deployed on January 1, 2023.**

### CODE REVIEW

**Comment by plehegar** [comment]
Do not merge before January 1

**Comment by Ms2ger** [comment]
I'd suggest you fix the test failures this year, though

**Comment by deniak** [comment]
> I'd suggest you fix the test failures this year, though

Good point! It's now fixed.

**Review by marcoscaceres — APPROVED** [review]

**Comment by deniak** [comment]
After more discussions, it was decided the copyright should not include the ", Inc.". Another email will follow on spec-prod to explain the decision but in the meantime, the PR has been updated accordingly.

**Review by sidvishnoi — APPROVED** [review]
Should I merge and release this now?

**Comment by deniak** [comment]
> Should I merge and release this now?

Yes please. We are ready to accept the new copyright.

**Comment by sidvishnoi** [comment]
Released in v32.6.1

**Pull request merged**
