### PR TITLE
fix(respec2html): correctly import marked

### PR DESCRIPTION
**Pull request by sidvishnoi**
Caught in https://github.com/w3c/hr-time/pull/130
Will release ASAP.

### CODE REVIEW

**Comment by saschanaz** [comment]
Is this still a problem? I don't see the issue on ReSpec 27.0.5, so maybe fixed in their side?

**Review by saschanaz — APPROVED** [review]
Hmm, https://github.com/markedjs/marked/pull/2227 did remove the default export, so approving.

**Comment by sidvishnoi** [comment]
https://github.com/markedjs/marked/releases says use `const { marked }`

**Comment by sidvishnoi** [comment]
Weird it didn't trigger the error in your fork though.

**Comment by saschanaz** [comment]
Mystery 🤔

**Comment by sidvishnoi** [comment]
Released v27.0.6

**Comment by saschanaz** [comment]
Buried rather than solved, but yeah 😆

**Pull request merged**
