### PR TITLE
Feature/notoc

### LINKED ISSUE #419: fix-headers incorrectly messes with non-section headers
If a document has a bunch of h* elements within a section, where these elements are not ALL the same (e.g., the section heading is an h3 and all of the headings within the section are h4), this module will incorrectly match on the subheadings and tweak them.  Basically, the CSS selector is naive. Thanks @ianbjacobs for pointing this out.

### PR DESCRIPTION
**Pull request by gkellogg**
This adds support for the class "notoc" on a section to cause the section to be omitted from the TOC.
Fixes #419.

### CODE REVIEW

**Comment by halindrome** [comment]
I don't mind this, nor that it was merged.  However, for a11y purposes it may be the case that headers that are NOT in the ToC are also headers that should not be 'landmarks' from an ARIA perspective.  I will raise this with the PFWG since they are our experts on the topic.  @michael-n-cooper can you please put this on the agenda?

**Comment by michael-n-cooper** [comment]
My personal opinion is these sections should still be landmarks even if 
it the author prefers not to include them in the TOC. But that's just a 
personal opinion. I have put this on the agenda for the next PF editors 
meeting. Michael

**Comment by halindrome** [comment]
Thanks. On a related note, we probably shouldn't be using headers for the
role / state /property definitions in aria core since these are not really
sections... Also for the editors to hash out.

**Comment by michael-n-cooper** [comment]
PF editors discussed this and said don´t exclude sections from being landmarks just because they have been exluded from TOC. I think that means no change from current behaviour. Tangent issues are on future PF editors agenda but probably don't need to be tracked in this issue.

**Pull request merged**
