### PR TITLE
Missing the protocol

### PR DESCRIPTION
**Pull request by plehegar**
Missing the protocol otherwise. sorry.

### CODE REVIEW

**Comment by plehegar** [comment]
@halindrome sorry for missing this earlier :(

**Comment by marcoscaceres** [comment]
Ah, you caught it :) ignore my previous comments.

**Comment by halindrome** [comment]
It was supposed ... Oh. Crap.

**Comment by halindrome** [comment]
Nice catch.  Will merge and republish.

**Pull request merged**
