### PR TITLE
fix(w3c/templates/headers): Switch default license for unofficial drafts to 4.0 (#2493)

### LINKED ISSUE #2352: Default licence for unofficial drafts
## Important info

* URL to affected spec: N/A
* ReSpec version: 24.21.7
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

Currently, the default licence for unofficial drafts is CC-BY 3.0.

Shouldn't it be switched to the latest version - namey, 4.0 ?

### PR DESCRIPTION
**Pull request by pradeepgangwar**
@marcoscaceres Please review, and let me know if this requires additional changes.

Fixes #2352

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Seems one of the tests needs updating too. Please see the error log.

**Comment by pradeepgangwar** [comment]
@marcoscaceres Please check it now. I guess they were failing due to some other reasons. I rebased my PR.

**Comment by marcoscaceres** [comment]
ok cool. Thanks!

**Comment by marcoscaceres** [comment]
Thanks @pradeepgangwar!

**Pull request merged**
