### PR TITLE
Remove @@@ from sotd

### LINKED ISSUE #1494: What does handle @@@?
I found `@@@text@@@` forms in our SOTD template:

https://github.com/w3c/respec/blob/cb910fefe152db689659c6b16b319ffabcc1a239/js/w3c/templates/sotd.html#L37-L53

It seems they are not processed by handlebars or anything, what does handle them?

### PR DESCRIPTION
**Pull request by OrionStar25**
Fixes #1494 .
The url for team submission comment requires the submission year (not the published year) along with the comment number (serial no of what comment it was in that year).  Idk how to get the comment number.

### CODE REVIEW

**Comment by OrionStar25** [comment]
You mean for the comments? Yes that makes more sense!

**Comment by OrionStar25** [comment]
What's conf.additionalContent?

**Comment by marcoscaceres** [comment]
`additionalContent` seems to just be additional text content that can be added. You'll need to check where it is added tho.

**Comment by OrionStar25** [comment]
I'm sorry I can't seem to figure out where the generated file's url is being stored.
isDraftURI  has a default of true, and hence even when it's not mentioned, an undefined spec link is created. Is that the link I want?

**Comment by marcoscaceres** [comment]
Ok, let's take a step back and fix one thing at a time. I've reverted the changes. 

- [ ] Let's get the first commit to just remove the `teamSubmission`. 
- [ ] Figure out what the submission URL is. You need to go to the https://www.w3.org/Submission/ and have at how the URLs for submissions are structured.

**Comment by marcoscaceres** [comment]
So, for example:

```
https://www.w3.org/Submission/2017/SUBM-epub-mediaoverlays-20170125/
```

We can see that these parts:

 1. base: https://www.w3.org/Submission/
 1. year: 2017 
 1. "SUBM" - {short-name} - {publicationDate} 

So, from the `conf`, you need to dig through it and find something that matches the `publicationDate`.  

You can do that by doing `console.log(conf)` and seeing what's available to you.

**Comment by OrionStar25** [comment]
`teamSubmissiom` removed. Onto the next part.

**Comment by OrionStar25** [comment]
`thisVersion`  happens to be the exact url that submitting members is hyperlinked with.  I can't seem to understand comment no though.

**Comment by OrionStar25** [comment]
@marcoscaceres

**Comment by marcoscaceres** [comment]
> thisVersion happens to be the exact url that submitting members is hyperlinked with.

Excellent! That makes it easy then. 

> I can't seem to understand comment no though.

@OrionStar25, not sure I understand what you are asking here? 

Regarding the failure on Travis:

```
  W3C — Headers
    Member-SUBM
      ✖ uses the right SoTD boilerplate for Member submissions
        HeadlessChrome 65.0.3325 (Linux 0.0.0)
      Expected 'foo' to match 'the Submitting Members have made a formal Submission request'.
          at <Jasmine>
          at UserContext.it (tests/spec/w3c/headers-spec.js:966:20)
          at <Jasmine>
```

Seems that there is a test that needs to be updated.

**Comment by OrionStar25** [comment]
> not sure I understand what you are asking here?

Every W3C staff comment is of this form : https://www.w3.org/Submission/2015/03/Comment/

So:
it has a base + thisVersion year +  comment number in that year + "Comment".
How do I retrieve the comment number?

> Seems that there is a test that needs to be updated.

That test should actually work though, but I'll try to fix it.

**Comment by OrionStar25** [comment]
Okay, so these are 2 differen specs both submitted in the same year:

https://www.w3.org/Submission/2017/01/Comment/
https://www.w3.org/Submission/2017/02/Comment/

> I think we need to derive it from person writing the spec

How would the spec writer know how many specs have been added before his in that year, unless he checks it up? I mean, is that what we want? For him to manually look up his order of spec in that year? That can lead to clashes too (If 2 concurrent specs are being written).

**Comment by marcoscaceres** [comment]
@OrionStar25, about the comments, I think it's fine, because it's super rare. The member submissions are managed by W3C Team, and they know what they are doing :) This is just to help them a little bit.

**Comment by OrionStar25** [comment]
@marcoscaceres `thisVersion` made me understand how I could retrive the year. Its working now. Also, added a `submissionCommentNumber`

**Comment by marcoscaceres** [comment]
Ok, now we need to just add 2 tests:

- [ ] check to make sure the @@@ is replaced with a the expected URL. 
- [ ] check the comments link is as we expect it.

**Comment by OrionStar25** [comment]
@marcoscaceres please review! Build fail is due to `run headless-timeout`.

**Comment by OrionStar25** [comment]
@marcoscaceres please review!

**Comment by OrionStar25** [comment]
Shouldnt we add a configuration option for submissionCommentNumber in the user guide?

**Comment by marcoscaceres** [comment]
Yep, that should be added to the wiki.

**Comment by marcoscaceres** [comment]
I need to work out what's happened with the formatting of the file before merging this. The original stod is formatted differently. 

See also the message I sent you on Slack. We should fix up your prettier configuration, as it's adding "," in various places.

**Comment by marcoscaceres** [comment]
respec@20.3.0

**Comment by marcoscaceres** [comment]
Documentation: https://github.com/w3c/respec/wiki/submissionCommentNumber

@OrionStar25 ^^^ please check. 👀

**Comment by OrionStar25** [comment]
Perfect!

**Comment by OrionStar25** [comment]
Need to also update this. https://github.com/w3c/respec/wiki/specStatus
`Team Submission` would be removed and `submissionCommentNumber` shall be added as necessary for member comment. (But then I'm thinking comments aren't compulsory).

**Pull request merged**
