### PR TITLE
fix: reindent after markdown processing

### LINKED ISSUE #2700: indentation in codeblocks still doesn't work with markdown
I've had many issues trying to make markdown work. 

* using triple backticks for codeblocks with markdown, indentation is broken (everything is flushed to the left)
* after converting codeblocks to `<pre class="rust"></pre>`, codeblock does not work anymore because I use `data-include` to include my code within the html file:

```
<section 
data-include="consensus_fixed.md"
data-include-format="text"
data-format="markdown">
</section> 
```

* inlining my markdown within the file, and with `<pre class="rust">`,  indentation only works for the first tab, not for others.

### PR DESCRIPTION
**Pull request by saschanaz**
Closes #2700

Extracted from #2650. Previously indentation collapsing happened before markdown processing, which confused the parser library.

### CODE REVIEW

**Comment by sidvishnoi** [comment]
Question: If a spec isn't using markdown but as `format: "markdown"`, will it fail?
[payment-request with markdown](https://respec-preview.netlify.com/?format=markdown&spec=https%3A%2F%2Fw3c.github.io%2Fpayment-request%2F&version=https%3A%2F%2Fdeploy-preview-2725--respec-pr.netlify.com%2Frespec-w3c.js) is failing

**Comment by saschanaz** [comment]
> Question: If a spec isn't using markdown but as `format: "markdown"`, will it fail?
> [payment-request with markdown](https://respec-preview.netlify.com/?format=markdown&spec=https%3A%2F%2Fw3c.github.io%2Fpayment-request%2F&version=https%3A%2F%2Fdeploy-preview-2725--respec-pr.netlify.com%2Frespec-w3c.js) is failing

Technically yes, because markdown is not a superset of HTML.

**Comment by saschanaz** [comment]
normalizePadding is the culprit in that specific case, though 🤦‍♀️

**Comment by sidvishnoi** [comment]
Checked enough specs using `format: markdown` and `data-include`. All looks fine.

**Comment by sidvishnoi** [comment]
Note: 
PASS: https://w3c.github.io/manifest/?format=markdown
FAIL:  https://respec-preview.netlify.com/?format=markdown&spec=https://w3c.github.io/manifest/&version=https://deploy-preview-2725--respec-pr.netlify.com/respec-w3c.js

**Comment by saschanaz** [comment]
Sigh, will check tomorrow again that whether it should be fixed and how.

**Comment by saschanaz** [comment]
Okay, given that

1. the behavior is extremely hard to fix because `normalizePadding` is a shit
2. per https://github.com/w3c/respec/pull/2725#issuecomment-575616253 specs look okay for now,

I'll defer the fix for #2715 and merge this in the approved state.

**Comment by marcoscaceres** [comment]
This is not a reprimand... just some history
 
> the behavior is extremely hard to fix because normalizePadding is a shit

Very true 🥺 The `normalizePadding()` code was trying to handle a bunch of regrettable assumptions that were made back in 2012 about how this would be used (e.g., `<section>` level markdown with special handling for `pre` etc... which made the whole thing insane. I think I spent like 6 weeks on it trying to deal with special cases). Anyway, I'm hopeful it will die too.

**Pull request merged**
