### PR TITLE
feat(ui): update ReSpec UI 

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by halindrome** [comment]
Is there documentation on the exported UI?  I know that ARIA could use being able to extend the menu.

**Comment by marcoscaceres** [comment]
@halindrome it's basically what is in:
https://github.com/w3c/respec/blob/develop/js/core/ui.js

We need to remove the rest of the jQuery `.css()` garbage in there (to respect2.css). Then we should have a fairly clean file to work with.

**Comment by halindrome** [comment]
Sure...  also, why respect2.css instead of respec2.css ?

**Comment by marcoscaceres** [comment]
> On 13 Oct. 2016, at 10:07 pm, Shane McCarron <notifications@github.com> wrote:
> 
> Sure... also, why respect2.css instead of respec2.css ?
> 
Typo on my part. We should drop the 2 also:)

**Pull request merged**
