### PR TITLE
Feat (headless.js): improved progress reporting.

### PR DESCRIPTION
**Pull request by marcoscaceres**
depends on #678.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@halindrome, could please review?

**Comment by halindrome** [comment]
My dev server got hacked so I need to rebuild it before I can actually test branches again.  Should happen over this weekend.  Sorry :(

**Comment by marcoscaceres** [comment]
Whoa! that sucks. Np. Hope nothing was compromised/stolen!

**Comment by dontcallmedom** [comment]
LGTM

**Pull request merged**
