### PR TITLE
Removed some conditional style changes

### PR DESCRIPTION
**Pull request by halindrome**
There were some conditional changes for the new styles that should now
be permanent.

### CODE REVIEW

**Comment by halindrome** [comment]
This change has no merge conflicts, and I do not believe it will cause any tests to fail.... but the tests won't run so I don't *know*.  Suggestions @marcoscaceres ?

**Comment by marcoscaceres** [comment]
LGTM, but let's make the test runner happy before we merge.

**Comment by marcoscaceres** [comment]
@halindrome, give this a rebase, see how it goes so far...

**Comment by halindrome** [comment]
I think what you are suggesting is that I checkout the branch, rebase it against origin/develop, and recommit.  Is that correct?

**Comment by marcoscaceres** [comment]
@halindrome yep: just do...

```
git checkout example_fix
git rebase develop 
```

**Comment by halindrome** [comment]
I don't think that will do anything but okay (remember I am running git 1.7.1)

**Comment by marcoscaceres** [comment]
@halindrome will be fine :)

**Comment by halindrome** [comment]
Uggh - test passes in one case and not in another.  @marcoscaceres help?

**Comment by marcoscaceres** [comment]
> On 3 Mar 2016, at 5:00 AM, Shane McCarron <notifications@github.com> wrote:
> 
> Uggh - test passes in one case and not in another. @marcoscaceres help?
> 

Will take a look in a bit

**Comment by marcoscaceres** [comment]
@halindrome looks like you branched off somewhere strange. It contains a bunch of commits that should not be there.

**Comment by halindrome** [comment]
Oh good.   UGGH.  I loathe git.

On Thu, Mar 3, 2016 at 6:54 AM, Marcos Caceres <notifications@github.com>
wrote:

> @halindrome <https://github.com/halindrome> looks like you branched off
> somewhere strange. It contains a bunch of commits that should not be there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3c/respec/pull/588#issuecomment-191750845>.
>



-- 
Shane McCarron
halindrome@gmail.com

**Comment by halindrome** [comment]
I am going to destroy this PR in favor of a new one 'cause of the testing issues and merge nonsense.

**Pull request closed without merging**
