### PR TITLE
Bug291 no rec track should add note

### PR DESCRIPTION
**Pull request by marcoscaceres**
Review please :smile:

### CODE REVIEW

**Comment by halindrome** [comment]
Did someone ask for this change?  I don't remember a bug report about it.

**Comment by marcoscaceres** [comment]
It's in the 3.2 milestone (see #291). Robin filed it. I'm working my way through the 3.2 list.

**Comment by halindrome** [comment]
Oh!  Then sure.  It LGTM.  However, if we could fix the critical path problem with data-oninclude first that would be super helpful.

**Comment by marcoscaceres** [comment]
Will try to do the data-oninclude today.

**Pull request merged**
