### PR TITLE
fix(core/link-to-dfn): add definitionMap back to conf

### PR DESCRIPTION
**Pull request by sidvishnoi**
Closes https://github.com/w3c/respec/issues/2848

### CODE REVIEW

**Comment by sidvishnoi** [comment]
@jnurthen Can you validate the behavior by 
replacing https://www.w3.org/Tools/respec/respec-w3c-common
with https://deploy-preview-2849--respec-pr.netlify.app/respec-w3c-common.js?

It won't throw error, but please verify links work as before.

**Comment by jnurthen** [comment]
It runs now but it isn't removing the elements from definitionMap. I think this is because it used to be case sensitive but no longer is and is all lower-case. Is this correct? Happy to modify our code for this change.

**Comment by sidvishnoi** [comment]
> I think this is because it used to be case sensitive but no longer is and is all lower-case. Is this correct?

Yes. It's all lowercase now. Hopefully doesn't break your code much. Let me know how it goes.

**Comment by jnurthen** [comment]
So this lets me update definitionMap but the terms are still appearing in the respec List of Definitions and any normative or infomormative references which the definition pulls into the document is still appearing in the references list.

**Comment by sidvishnoi** [comment]
Can you try using https://unpkg.com/respec@24.38.1/builds/respec-w3c-common.js and share what terms should not appear?
I tried to use v24.38.1 (this is what https://www.w3.org/TR/wai-aria-1.2/ used) on https://github.com/w3c/aria/commit/f519fca855c11004f35b22ed127077414a3af0ea (as this was the last commit before December update), but I found differences between the TR version and my local one even with same ReSpec version.

**Comment by sidvishnoi** [comment]
Closing as w3c-common profile is no longer maintained. Read [migration guide](https://github.com/w3c/respec/wiki/respec-w3c-common-migration-guide) in wiki.

**Pull request closed without merging**
