### PR TITLE
Adds "preview" status, for @tobie previews

### PR DESCRIPTION
**Pull request by marcoscaceres**
* makes specs unofficial when previewing

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@tobie, this now will set things to unofficial and add a warning if the spec status is "unofficial". When you generate the spec, can you please add `?specStatus=unofficial` to the URL.

**Comment by tobie** [comment]
Might also be worth adding a link back to the PR, etc.

**Comment by tobie** [comment]
OK, shipped and deployed this. LMK how it goes?

**Comment by tobie** [comment]
Oh, wait! Do you want `specStatus=preview` or `specStatus=unofficial`?

**Comment by marcoscaceres** [comment]
specStatus=preview

**Comment by tobie** [comment]
Fixed.

**Comment by tobie** [comment]
This seems to be breaking specs which now reference missing resources on w3.org, e.g.: https://s3.amazonaws.com/pr-preview/w3c/webrtc-pc/issue-1470-patch.html

**Comment by marcoscaceres** [comment]
@tobie thanks for trying it out. Upon reflection, I think what I actually want here is only to signal that it's a preview (`?isPreview=true`), which will add the ugly red-annoying-box but not change the status.

It occurred to me me that Keeping the spec status is useful for checking snapshots against PubRules etc. I'll update the PR and ping you to change things again on your side (to append  `isPreview=true` on your end). Appreciate your time and help with this!

**Comment by tobie** [comment]
Added isPreview=true.

**Comment by marcoscaceres** [comment]
@tobie, I'll implement the branch thing separately. Might need to chat to you about it in IRC. There are a few things that could work, like: 

`?isPreview=true&github={"branch": "branch", repoURL: "https://github.com/w3c/repo"}`

Then I can key off `github` there to provide the link back, similar the WHATWG specs. However, I don't know how useful that is, as people don't generally browse branches (maybe I'm missing something).

**Comment by tobie** [comment]
I was mostly just thinking about having a link back to the PR. Useful in case you land on it and want the broader context and/or the merge status.

**Comment by tobie** [comment]
You can get that easily from the [config object](https://github.com/tobie/pr-preview#params-optional):
```json
{
    "params": {
        "prUrl": "{{ pull_request.html_url }}",
        "prNumber": "{{ pull_request.number }}"
    }
}
```

So it's trivial to add them to extra/default params in the URL.

**Comment by marcoscaceres** [comment]
oh, nice! Ok, would need to add those to ReSpec - but would be trivial.

**Comment by tobie** [comment]
Well, LMK which ones you'll need. :)

**Comment by marcoscaceres** [comment]
@tobie will do! Will try to hack on it next week.

**Pull request merged**
