### PR TITLE
Try to figure out why Chrome keeps failing

### PR DESCRIPTION
**Pull request by marcoscaceres**
* disabling firefox, which is working fine...

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Ok, it was running both browsers at the same time that was causing the issues. 

@halindrome r?

**Comment by marcoscaceres** [comment]
I also switched to Mocha style reporting because it's :rainbow: pretty.

**Comment by marcoscaceres** [comment]
I'm merging this one because: 
 * it will fix all my other prs
 * it's a tiny change. 
 * it doesn't affect end-users - only maintainers. 

However, a post approval would be great.

**Comment by halindrome** [comment]
Seems to have helped in my dev environment.

**Pull request merged**
