### PR TITLE
fix(core/webidl): indent stringifiers

### LINKED ISSUE #1599: IDL stringifier is causing RangeError
## Important info

* URL to affected spec: https://w3c.github.io/selection-api/
* ReSpec version: 20.4.0.
* [x] I did a "hard refresh", but it's still busted. 

## Description of problem

Expected:
Selection interface should be displayed correctly. 

But what actually happened (the bug):
The IDL below throws: 

```
RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at pads (webidl.js:204)
    at Object.<anonymous> (webidl.js:105)
    at Object.main (templates.js:361)
    at main (handlebars.js:1145)
    at ret (handlebars.js:1148)
    at writeMethod (webidl.js:701)
    at webidl.js:604
    at Array.map (<anonymous>)
    at writeInterfaceDefinition (webidl.js:599)
```
Optional, steps to reproduce: 

Given: 
```IDL
interface Selection {
          stringifier DOMString ();
};
```

Seems this has regressed. It seems our friend "pads()" is again getting negative values:

```JS
function pads(num) {
  return " ".repeat(num);
}
```

### PR DESCRIPTION
**Pull request by marcoscaceres**
* fixes #1599

### CODE REVIEW

**Comment by saschanaz** [comment]
LGTM but a test is required.

**Comment by marcoscaceres** [comment]
That's the weird things... we did have tests... ("MethBasic" in "tests/spec/core/webidl.html") :( Adding some more tho.

**Comment by saschanaz** [comment]
The existing test currently only effectively tests the longest indentation (so only `static Promise&lt;RTCCertificate>` now). That's why the test couldn't catch this problem.

**Comment by marcoscaceres** [comment]
Yeah, spotted it. Whoopsy. Incoming tests.

**Comment by marcoscaceres** [comment]
Figures I'd add independent tests for each special type. Then we can more easily catch regressions if we ever deal types independently.

**Pull request merged**
