### PR TITLE
refactor(core/structure): localize module 

### PR DESCRIPTION
**Pull request by ThobyV**
P.R to add localization in respect to issue https://github.com/w3c/respec/issues/2084 for the module `structures.js`.  I think this is last module in /core that needs localization. Thanks @marcoscaceres  and everyone for review! Will make sure to complete the rest asap.

### CODE REVIEW

**Comment by ThobyV** [comment]
Thanks @marcoscaceres. Do you think I would be able to send a pre-proposal for early review or  wait until gsoc official time?

**Comment by marcoscaceres** [comment]
Send me an email and let's discuss (marcos@marcosc.com)!

**Comment by marcoscaceres** [comment]
Quick `git grep --name-only conf.l10n src` shows the following modules still need localization (@ThobyV, not asking you to do these... just so I have an idea of where we are at!):  

src/core/figures.js
src/core/github.js
src/core/issues-notes.js

And: 
src/w3c/headers.js
src/w3c/templates/cgbg-headers.js
src/w3c/templates/cgbg-sotd.js
src/w3c/templates/headers.js
src/w3c/templates/sotd.js

**Comment by ThobyV** [comment]
@marcoscaceres I think those modules left in /core have localization which are not used in the interface, would they still be refactorable?

**Comment by marcoscaceres** [comment]
Not sure I understand what you mean @ThobyV. Could you please clarify? 

Looking at figures.js, we could definitely fold `conf.l10n.fig` into the figures.js file.

**Pull request merged**
