### PR TITLE
chore(package): update to webidl2@18

### PR DESCRIPTION
**Pull request by saschanaz**
Closes #2177 
Closes #2176 

Oops, didn't know you already opened a PR 😅

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Added closes above so to close the others :)

**Comment by marcoscaceres** [comment]
🚢 it?

**Comment by saschanaz** [comment]
Yup 🚀

**Comment by marcoscaceres** [comment]
+ respec@24.5.3 

Great work! Hope I get time to jump into the validator. Want to find time to re-read the IDL spec and add validation rules as a way of catching up on the spec changes.

**Pull request merged**
