### PR TITLE
Feat(global): link to HTTPS urls (closes #749)

### LINKED ISSUE #749: Support for https in /TR
From the [proposal](https://lists.w3.org/Archives/Public/spec-prod/2016AprJun/0024.html):

- [x] link to TR stylesheets
- [x] links to W3C logo and W3C main homepage
- [x] ALL document identifiers ("This Version", "Latest Version", "Previous
Version", etc.)
- [x] links to W3C IPR notice, liability, trademark, and document use
- [x] link to the W3C technical reports index
- [x] links to W3C Patent Policy, patent disclosures, and W3C Process
- [x] link to fixup.js and other supported scripts
- [x] links to errata page and translation
- [x] links to ReSpec guide

### PR DESCRIPTION
**Pull request by marcoscaceres**
@plehegar r?

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/respec/782)

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Fixed tests

**Comment by marcoscaceres** [comment]
All the links appear to work fine

**Comment by marcoscaceres** [comment]
@plehegar, @dontcallmedom is it ok to merge and release this? Or do we need to wait for some particular date?

**Comment by marcoscaceres** [comment]
Rebased

**Comment by plehegar** [comment]
Until we make the switch official, you shouldn't release this, otherwise it's going to break publications. And we can't make the switch until we get an ok on the specref side :(

**Comment by marcoscaceres** [comment]
@plehegar, maybe we can land this in pieces? Like we could start with some of the URLs that don't relate to the publication (e.g., boilerplate ones). Can pubrules handle those?

**Comment by marcoscaceres** [comment]
@plehegar ping

**Comment by marcoscaceres** [comment]
Rebased... blocked on #792

**Comment by halindrome** [comment]
@deniak pointed out that the patentURI reference is http:.   this URI and some others are supplied by the spec.  If any of these URIs point into w3.org I imagine we should just change them to https - right?

**Comment by marcoscaceres** [comment]
Correct. The linter should already catch these and ask the editor to change them. 

We could auto-fix these on spec generation, however.

**Comment by marcoscaceres** [comment]
> @deniak pointed out that the patentURI reference is http:.

to be clear, that was a mistake in my spec, not a mistake with ReSpec.

**Pull request merged**
