### PR TITLE
fix(w3c/templates/sotd): remove old patent policy text

### LINKED ISSUE #1443: Upcoming update to WG notes patent policy text
@plehegar and @wseltzer agreed to simplify the patent policy text for **WG Notes** (other types of documents remain unchanged).
After https://github.com/w3c/specberus/pull/707 is merged, the markup should simply be:
```html
<p data-deliverer="@@Working Group ID@@">
  This document was produced by a group operating under the  <a href="https://www.w3.org/Consortium/Patent-Policy/"><abbr title="World Wide Web Consortium">W3C</abbr> Patent Policy</a>.
</p>
```

Note: we are adding a requirement on the `data-deliverer` attribute which should list the WG IDs which was already in one of the previous patent policy link.

Once we are certain respec and bikeshed have been updated, we will update pubrules.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes  #1443

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Ah, got it. ok. Thanks @deniak!

**Comment by marcoscaceres** [comment]
Doing this again.

**Comment by marcoscaceres** [comment]
@deniak, you are absolutely sure you want it for IG-NOTEs, right? Currently, for IG-NOTEs we exclude this entirely.

**Comment by marcoscaceres** [comment]
To be clear, IG-NOTES will be:

> This document was produced by a group operating under the W3C Patent Policy. The disclosure obligations of the Participants of this group are described in the charter.

That make sense, I guess.

**Comment by marcoscaceres** [comment]
Ok, but it does need to disclosure obligations bit, right?: https://www.w3.org/pubrules/doc/rules/?profile=IG-NOTE#patPolReq

**Comment by deniak** [comment]
> Ok, but it does need to disclosure obligations bit, right?: https://www.w3.org/pubrules/doc/rules/?profile=IG-NOTE#patPolReq

Yes, we still need that bit.

**Pull request closed without merging**
