### PR TITLE
Fix source maps

### PR DESCRIPTION
**Pull request by marcoscaceres**
@halindrome, this gets source maps working correctly. I still think we need to try this out a bit before we commit to it. According the [RequireJS documentation](http://requirejs.org/docs/optimization.html#sourcemaps), source maps are still "experimental".

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Ok, this gives us the first steps towards using source maps in testing. However, browser support is spotty. 

@halindrome, r?

**Comment by marcoscaceres** [comment]
@halindrome, while I fix the other ones, I'd like to get this landed. If you have time, would really appreciate a review. 

Other people watching this repo, can anyone else help with reviews?

**Comment by marcoscaceres** [comment]
Ping

**Comment by halindrome** [comment]
Looking.

**Comment by halindrome** [comment]
Tests seem to pass - LGTM.

**Pull request merged**
