### PR TITLE
Revert "feat(core/github-api): Centralised Github Fetching And Rate L…

### PR DESCRIPTION
**Pull request by marcoscaceres**
…imiting using API v3 (#2181)"

This reverts commit ac084e80ecbde461b91931c7c2f62db877686821.

Fails after merge: 
```
  Core — Issues and Notes
    ✖ should link to GitHub issue tracker for features at risk
      HeadlessChrome 74.0.3723 (Linux 0.0.0)
    TypeError: Cannot read property 'querySelectorAll' of null
        at <Jasmine>
        at UserContext.<anonymous> (tests/spec/core/issues-notes-spec.js:356:31)
    ✖ marks closed issues as closed in the spec
      HeadlessChrome 74.0.3723 (Linux 0.0.0)
    Error: Expected false to be truthy.
        at <Jasmine>
        at UserContext.<anonymous> (tests/spec/core/issues-notes-spec.js:251:52)
    ✖ sets aria-label to reflect the labels from Github
      HeadlessChrome 74.0.3723 (Linux 0.0.0)
    Error: Expected null to be truthy.
        at <Jasmine>
        at UserContext.<anonymous> (tests/spec/core/issues-notes-spec.js:296:7)
    ✖ renders the original issue post in an empty issue block
      HeadlessChrome 74.0.3723 (Linux 0.0.0)
    Error: Expected '' to be 'Issue 1540: A mock open issue for testing refactorbugblanknot-a-colorThe issue contentThe second paragraph'.
        at <Jasmine>
        at UserContext.<anonymous> (tests/spec/core/issues-notes-spec.js:310:35)
    ✖ shows labels for github issues
      HeadlessChrome 74.0.3723 (Linux 0.0.0)
    TypeError: Cannot read property 'textContent' of null
        at <Jasmine>
        at UserContext.<anonymous> (tests/spec/core/issues-notes-spec.js:149:23)
```

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Having to back this out due to failures above. No big deal tho @devanshbatra04 - however, you will need to check what happened locally.

**Comment by saschanaz** [comment]
Tests passed on the PR and now fail? Hmm.

**Comment by marcoscaceres** [comment]
> Tests passed on the PR and now fail? Hmm.

Yeah. Weird.

**Comment by saschanaz** [comment]
We are forcing the PRs get latest commits from the main branch before merging, which should mean we ran the tests on exactly same code. Weird indeed... 🤔

**Comment by marcoscaceres** [comment]
Trying it once again, just in case:
https://travis-ci.org/w3c/respec/builds/510890385

**Comment by devanshbatra04** [comment]
The tests passed this time :/

**Comment by devanshbatra04** [comment]
They do pass on my local after merging too.

**Comment by devanshbatra04** [comment]
I believe I do understand. When I switch off my internet they fail. It's something related to the stubs these tests are using, also they are definitely making the actual http requests.
I will rewrite these tests in the same PR?

**Comment by saschanaz** [comment]
Looks like somehow GitHub randomly failed to give a correct response then.

**Comment by devanshbatra04** [comment]
The request probably never went through the VM firewall.

**Comment by marcoscaceres** [comment]
Yeah, looks like it's ok. I guess connection must have failed on their end.

**Comment by devanshbatra04** [comment]
As a safeguard, I will add a stub to the tests so that remaining github requests is always returned 60 and no http request gets made. This way, the tests will continue to work offline.

**Comment by marcoscaceres** [comment]
Sounds good.

**Comment by marcoscaceres** [comment]
just remebering that we have stubs already: https://github.com/w3c/respec/tree/develop/tests/data/issues 

I think this was just a random anomaly. No neex to add anything.

**Comment by devanshbatra04** [comment]
I created a new function to get actual remaining requests from github. We couldnt have stubs for that. 
Before it used to be hardcoded to 60

**Comment by marcoscaceres** [comment]
Oh woops! That should not have hard-coded the Github URL - not sure how we all missed that. It should use the API link from the config object. Then we can pull the data from localhost.

**Comment by marcoscaceres** [comment]
Filed https://github.com/w3c/respec/issues/2195

**Pull request closed without merging**
