### PR TITLE
Export config fixup

### PR DESCRIPTION
**Pull request by marcoscaceres**
* exporting the intial config was having issues if the userConfig was before or after the respec.js file. This hopefully fixes that now.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@tobie r?

**Comment by tobie** [comment]
LGTM though a test would have been welcomed for this case (not sure if feasible).

**Comment by marcoscaceres** [comment]
Not to worry, there is test already from the previous attempt :)

**Comment by tobie** [comment]
:+1:

**Pull request merged**
