### PR TITLE
Use fetch instead of ajax

### PR DESCRIPTION
**Pull request by marcoscaceres**
Sending for testing ... this includes #623.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
This is good to go (if tests pass :))

**Comment by halindrome** [comment]
I need a little time to look this one over / test it.  I am theoretically on vacation and then at the W3C AC meetings for the next 3 days but I will try to play with it when the AC sessions get boring!

**Comment by marcoscaceres** [comment]
@halindrome, np. Looking forward to hearing what you think.

**Comment by marcoscaceres** [comment]
ping

**Comment by halindrome** [comment]
LGTM although I am worried about legacy browser support.  I assume the whatwg-fetch shim is rock solid, but I don't know anything about it.  I also note that there is a fetch function in the github.js module?

**Comment by marcoscaceres** [comment]
> LGTM although I am worried about legacy browser support. I assume the whatwg-fetch shim is rock solid, but I don't know anything about it.

It just wraps XHR. The polyfill is fairly simple. 

> I also note that there is a fetch function in the github.js module?

Yep, that one just wraps $.ajax also.

**Pull request merged**
