### PR TITLE
WIP(respec2html): Externalize fetch and write

### PR DESCRIPTION
**Pull request by marcoscaceres**
@dontcallmedom WDTY? 

```JS
const fetchAndWrite = require("./tools/respecDocWriter.js").fetchAndWrite;
const src = "https://w3c.github.io/manifest/";
const out = "path/to/out"; // or null for stdout
const whenToHalt = {
  haltOnError: true,
  haltOnWarn: true,
};
const timeout = 10000;
fetchAndWrite(src, out, whenToHalt, timeout).then(() => console.log("done") );
```

### CODE REVIEW

**Comment by marcoscaceres** [comment]
(updated example above to show it returns a promise)

**Comment by marcoscaceres** [comment]
@dontcallmedom, have a play and let me know if it's ok for the w3c spec-generator.

**Comment by dontcallmedom** [comment]
for the spec generator, instead of writing to a file it would be best if I could have the content itself (since I'm serving it back via http)

**Comment by marcoscaceres** [comment]
Np, I'll return it with the promise. Otherwise, just set out to null and pipe it straight from process.stdout

**Comment by dontcallmedom** [comment]
Hi @marcoscaceres I don't think respec2html.js has been updated to return the data directly yet, but I need to update the spec generator; since new respec has been released, this is kind of urgent now

**Comment by marcoscaceres** [comment]
@dontcallmedom, correct. Let me do that now for you 🔧

**Pull request merged**
