### PR TITLE
fix(w3c/headers): typo

### LINKED ISSUE #1656: "stod" typo in src/w3c/headers.js?
Sorry, not following the issue template. I just stumbled into what looks like a typo while having a look at the code. I don't even know whether this has any practical impact on existing specs.

At: https://github.com/w3c/respec/blob/develop/src/w3c/headers.js#L520
I suspect `stod` should be `sotd`.

You might want to update the variable name in https://github.com/w3c/respec/blob/develop/tests/spec/w3c/headers-spec.js#L1018 as well.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #1656

### CODE REVIEW

**Comment by sidvishnoi** [comment]
Are we sure that no specs would be affected?

**Comment by marcoscaceres** [comment]
Only in a good way :)

**Comment by sidvishnoi** [comment]
Just a second late, maybe also fix this: https://github.com/w3c/respec/blob/6e8bcde9c0844128e121c650e09aca874486a737/tests/spec/w3c/headers-spec.js#L1018

**Comment by marcoscaceres** [comment]
fixed here https://github.com/w3c/respec/pull/1658

**Pull request merged**
