### PR TITLE
fix(w3c/sotd): update link to process 2023

### PR DESCRIPTION
**Pull request by deniak**
Starting from July 17 2023, pubrules will no longer accept documents published under the process 2021.
That PR updates the link with the 2023 process and should be merged on that date.

/cc @plehegar

### CODE REVIEW

**Review by sidvishnoi — APPROVED** [review]

**Comment by deniak** [comment]
Thanks @sidvishnoi. I'll let you when this PR can be merged.

**Review by marcoscaceres — APPROVED** [review]

**Comment by deniak** [comment]
@sidvishnoi @marcoscaceres  I'm expecting to update pubrules and echidna around 4pm UTC today. I'll let you know when it's done so you can merge that PR.
Please let me know if the timing doesn't work for you.

**Comment by sidvishnoi** [comment]
4pm UTC works for me. 30-60 minutes earlier would be even better.

**Comment by deniak** [comment]
> 4pm UTC works for me. 30-60 minutes earlier would be even better.

I'll try to deploy a bit earlier but we also need to sync the changes in bikeshed. Note that I can merge the PR myself if this is more convenient.

**Comment by sidvishnoi** [comment]
No worries, let me know when and I'll merge and release.

**Comment by deniak** [comment]
@sidvishnoi feel free to merge that PR. The publication tools should now accept documents produced under the process 2023

**Comment by deniak** [comment]
Thanks @sidvishnoi !

**Pull request merged**
