### PR TITLE
fix(respec2.css): th code inherit color (closes #877)

### LINKED ISSUE #877: More granular styles for "table.simple th code" with better legibility/contrast
See for instance the simple tables at https://w3c.github.io/pointerevents/#dom-pointerevent-pointertype and https://w3c.github.io/pointerevents/#the-buttons-property - with current styles, using `<code>` in a `<th>` results in an unreadable color combination with a very low color contrast.

74437974-4d70-11e6-926a-30a2203cb298

Is this something that can/should be fixed here in respec? Not sure if this is a common use pattern.

x-ref https://github.com/w3c/pointerevents/issues/112

### PR DESCRIPTION
**Pull request by marcoscaceres**
@patrickhlauke wdyt?

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Just inherits from table: 

screenshot 2016-07-20 18 54 01

**Comment by patrickhlauke** [comment]
me gusta. +1

**Comment by halindrome** [comment]
LGTM but I wonder if someone from A11Y can check it for WCAG color contrast requirements?

**Comment by patrickhlauke** [comment]
foreground `#fff`, background `#005a9c` - color contrast ratio 7.1:1, well above the minimum 4.5:1

in short, yup, looks good.

**Comment by marcoscaceres** [comment]
Thanks you both! Will release first thing tomorrow.

**Pull request merged**
