### PR TITLE
fix(assets/issues-notes): fix warning icon styling

### PR DESCRIPTION
**Pull request by dbass2**
Updated CSS to change the size and location of the icon displayed

### CODE REVIEW

**Comment by ZoeBijl** [comment]
Resolves #2531

**Comment by dbass2** [comment]
So testing the change… how long does it take to see the change for validation?

This was warning icon I was using to test with but I do not see it yet.
https://w3c.github.io/aria-practices/#naming_with_aria-labelledby

**Comment by ZoeBijl** [comment]
@dbass2 this PR will have to be reviewed by someone. After that it will have to be merged into the ReSpec master branch. Once that is done you should see the change the next time you load the Authoring Practices Editors Draft.

**Comment by marcoscaceres** [comment]
Could you please upload a quick screenshot of what it looks like now? Also, did you check it on a mobile device to make sure it’s ok there too?

**Comment by sidvishnoi** [comment]
You can also preview it using [respec-preview](https://respec-preview.netlify.com/?spec=https%3A%2F%2Fw3c.github.io%2Faria-practices%2F&version=https%3A%2F%2Fdeploy-preview-2539--respec-pr.netlify.com%2Frespec-w3c.js) 😅

**Comment by marcoscaceres** [comment]
D1DFAD79-ED83-4574-9415-4343FB3AF570

On my phone.

**Comment by ZoeBijl** [comment]
This is what I get in Chrome if I follow the “[fixed demo](https://respec-preview.netlify.com/?spec=https://rawcdn.githack.com/w3c/aria-practices/bc5b7ef61bc1013f57ec42351880054d0abe5179/aria-practices.html&version=https%3A%2F%2Fdeploy-preview-2539--respec-pr.netlify.com%2Frespec-w3c-common.js)” link:
A warning icon that is about the same height as the line height of text

 Same thing on my phone (iOS 13.1):
Same as previous image but the icon is coloured

**Comment by marcoscaceres** [comment]
I’ll do :)

**Comment by dbass2** [comment]
Testing for recommendations pre change, using browser F12 developer tools on 3 browsers.
Also recommend using rem instead of em but that is a diff matter.
Test Location: 5.3.2.3 Naming with Referenced Content Via aria-labelledby<https://w3c.github.io/aria-practices/#naming_with_aria-labelledby>
Before
[cid:image008.jpg@01D5833F.B41DAE40]
CSS Change Location: https://github.com/w3c/respec/blob/092e9788b58c342da35378ec29ef26fbb002b4c7/assets/issues-notes.css#L25
It is my opinion the big red box is enough to get my attention. I don’t need a big icon as well.
Let me know if Option 1 works, or if more  options are preferred.
Browsers tested: IE v11, Edge v41, Chrome v77.
Testing in safari is required but I don’t have one to test with. I kinda feel like if it works in Chrome it will work in Safari pretty equal.
NOTE: some browsers did not require all the properties I list below but others broke with removal.
This seemed to be a happy medium.
Change option using same CSS changes in two browsers
Remove:         height: 100%
vertical-align: top

Change:          font-sized: 1.3em
margin-top: -0.3em
Before

After

.warning-title::before {
    content: "⚠";
    font-size: 3em;
    float: left;
    height: 100%;
    padding-right: 0.3em;
    vertical-align: top;
    margin-top: -0.5em;
}

.warning-title::before {
    content: "⚠";
    font-size: 1.3em;
    float: left;
    padding-right: 0.3em;
    margin-top: -0.3em;
}


IE11
[cid:image001.jpg@01D5833C.AB73B120]

[cid:image002.jpg@01D5833C.AB73B120]


EDGE
[cid:image003.jpg@01D5833C.AB73B120]

[cid:image004.jpg@01D5833C.AB73B120]


Chrome
[cid:image005.jpg@01D5833C.AB73B120]

[cid:image006.jpg@01D5833C.AB73B120]

**Comment by ZoeBijl** [comment]
I did some digging around W3C’s base.css file and found there’s a style for issues that might be useful here:
A warning displayed in a box with a red background and a brighter red border on the left hand side
Does respec load the base.css by default?

**Comment by marcoscaceres** [comment]
Yes, base.css is loaded by default

**Comment by ZoeBijl** [comment]
Is there a reason ReSpec has its own warning style?

**Comment by marcoscaceres** [comment]
Legacy reasons, but I’ve been trying to get rid of it for a long time. Same with that warnings.

**Pull request merged**
