### PR TITLE
Feat(global): add hightlighter and beautifier as deps

### PR DESCRIPTION
**Pull request by marcoscaceres**
* adds to package dependencies: highlight.js and jsbeautifier
  * adds default options for beautifier (beautify-options.js)
  * tells builder to include highlighter and beautifier
  * Sets appropriate paths in profile-w3c-common.js

### CODE REVIEW

**Comment by marcoscaceres** [comment]
This is Part 1 of some incoming pull requests....

**Comment by marcoscaceres** [comment]
Once these land, I can send the rest.

**Comment by dontcallmedom** [comment]
@marcoscaceres I've looked at the changes and they look OK, but I was not sure what observable changes in the output of ReSpec I should be looking for — can you say a bit more?

**Comment by marcoscaceres** [comment]
@dontcallmedom nothing will change yet. This is just laying down the infrastructure. All the cool stuff if coming next :) 

It's all in this branch:
https://github.com/w3c/respec/commits/745_hightlighjs

**Comment by marcoscaceres** [comment]
@dontcallmedom, I have to send it in pieces, as they all build on each other and it's a lot of code that's about to come in. I also want to make sure tests keep passing, etc.

**Pull request merged**
