### PR TITLE
chore(tools/netlify): update preview app URL

### PR DESCRIPTION
**Pull request by sidvishnoi**

### CODE REVIEW

**Comment by deniak** [comment]
@sidvishnoi can you give it another try please?

**Comment by sidvishnoi** [comment]
Running in https://github.com/w3c/respec/actions/runs/9364185600

**Comment by sidvishnoi** [comment]
@deniak That worked! What was it?

**Comment by deniak** [comment]
We have some rate limiting rules in place. I relaxed them a little bit.

**Pull request merged**
